In [42]:
import cnn
import numpy as np
import imp
imp.reload(cnn)

params.keys()=
 dict_keys(['k0', 'gama0', 'beta0', 'k1', 'gama1', 'beta1', 'w2', 'gama2', 'beta2'])
params[k0]=
 [[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721 -0.10321885]]
params[k1]=
 [[ 0.4105985   0.14404357  1.45427351]
 [ 0.76103773  0.12167502  0.44386323]
 [ 0.33367433  1.49407907 -0.20515826]]
l= 3
loop 1: i= 2
Xi.shape bf = (2, 10, 1, 1)
Xi.shape= (2, 10, 1, 1)
XX.shape= (2, 10, 1, 10, 1, 1)
bf vi.shape= (2, 1, 1, 1)
vi.shape= (2, 1, 1, 1, 1, 1)
dXi_Zi.shape= (2, 10, 1, 10, 1, 1)
d_Xi.shape= (2, 10, 1, 1)
d_Zi.shape= (2, 10, 1, 1)
Ai_1.shape= (2, 28, 28, 1)
Ai_1_re.shape= (2, 784, 1, 1)
d_wi.shape= (2, 10, 784)
3: i= 2
Yi_1.shape= (2, 28, 28, 1)
g_d[i-1](Yi_1).shape= (2, 28, 28, 1)
d_Ai_1.shape= (2, 28, 28, 1)
loop 1: i= 1
Xi.shape bf = (2, 28, 28, 1)
Xi.shape= (2, 28, 28, 1)
XX.shape= (2, 28, 28, 28, 28, 1)
bf vi.shape= (2, 1, 1, 1)
vi.shape= (2, 1, 1, 1, 1, 1)
dXi_Zi.shape= (2, 28, 28, 28, 28, 1)
d_Xi.shape= (2, 28, 

<module 'cnn' from '/home/qc/proj_py/cnn.py'>

In [ ]:
grad[d_k0]=
 [[-1.05064404e-03  8.57372987e-04 -2.46263943e-03]
 [ 1.50711755e-03  9.83373378e-06  3.34937219e-04]
 [ 1.03349303e-03  6.98361136e-04  2.32028474e-04]]
grad[d_k1]=
 [[-0.08274247 -0.01308522 -0.04193828]
 [ 0.02752182  0.0410502  -0.07598211]
 [-0.00563553  0.05458701 -0.12164937]]