In [14]:
import cnn
import numpy as np
import imp
imp.reload(cnn)

params.keys()=
 dict_keys(['k0', 'gama0', 'beta0', 'k1', 'gama1', 'beta1', 'w2', 'gama2', 'beta2'])
params[k0]=
 [[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721 -0.10321885]]
params[k1]=
 [[ 0.4105985   0.14404357  1.45427351]
 [ 0.76103773  0.12167502  0.44386323]
 [ 0.33367433  1.49407907 -0.20515826]]
X.shape= (2, 28, 28, 1)
Ai_1.shape= (2, 28, 28, 1)
Ai_1.shape= (2, 28, 28, 1)
Ai_1.shape= (2, 28, 28, 1)
y=
 [[[[0.02372955 0.26360139 0.02886445 0.01670665 0.1003192  0.08533688
    0.36918726 0.02385651 0.03744285 0.05095526]]]


 [[[0.02206176 0.09000341 0.02316047 0.02104979 0.15847259 0.37938576
    0.14829108 0.01688439 0.07638095 0.0643098 ]]]]
y.shape= (2, 1, 10, 1)


<module 'cnn' from '/home/qc/proj_py/cnn.py'>