In [11]:
import cnn
import numpy as np
import imp
imp.reload(cnn)

xin.shape= (2, 784, 1)
grad_check: abs_error=
 {'d_w3': 57.273233215695704, 'd_gama3': 9.47652672800281e-06, 'd_beta3': 2.2121193765656244e-14, 'd_k2': 0.00014671533660562958, 'd_gama2': 3.130630754633046e-09, 'd_beta2': 0.004542770212265013, 'd_k1': 0.0055963892645448255, 'd_gama1': 6.661338147750939e-16, 'd_beta1': 0.024100989539015905, 'd_k0': 0.005407904372138916, 'd_gama0': 2.2908758223749714e-14, 'd_beta0': 0.004495225808123032}
grad_check: ratio_error=
 {'d_w3': 0.04617479221355107, 'd_gama3': 1.4011253971144827e-05, 'd_beta3': 0.9925280199252802, 'd_k2': 0.0001971808679784579, 'd_gama2': 9.998332066801227e-05, 'd_beta2': 0.003787255261514109, 'd_k1': 0.0072914145010349605, 'd_gama1': 0.015228426395939087, 'd_beta1': 0.13443118546437535, 'd_k0': 0.018189834855820028, 'd_gama0': 1.0, 'd_beta0': 0.009818484785253805}


<module 'cnn' from '/home/qc/proj_py/cnn.py'>

In [ ]:
col1=
 [[[[  0.   0.   0.   0.   5.   6.   0.   8.   9.]
   [  0.   0.   0.  13.  14.  15.  16.  17.  18.]
   [  0.   0.   0.  22.  23.  24.  25.  26.  27.]
   [  0.   0.   0.  31.  32.   0.  34.  35.   0.]]

  [[  0.  38.  39.   0.  41.  42.   0.  44.  45.]
   [ 46.  47.  48.  49.  50.  51.  52.  53.  54.]
   [ 55.  56.  57.  58.  59.  60.  61.  62.  63.]
   [ 64.  65.   0.  67.  68.   0.  70.  71.   0.]]

  [[  0.  74.  75.   0.  77.  78.   0.  80.  81.]
   [ 82.  83.  84.  85.  86.  87.  88.  89.  90.]
   [ 91.  92.  93.  94.  95.  96.  97.  98.  99.]
   [100. 101.   0. 103. 104.   0. 106. 107.   0.]]

  [[  0. 110. 111.   0. 113. 114.   0.   0.   0.]
   [118. 119. 120. 121. 122. 123.   0.   0.   0.]
   [127. 128. 129. 130. 131. 132.   0.   0.   0.]
   [136. 137.   0. 139. 140.   0.   0.   0.   0.]]]


 [[[  0.   0.   0.   0. 149. 150.   0. 152. 153.]
   [  0.   0.   0. 157. 158. 159. 160. 161. 162.]
   [  0.   0.   0. 166. 167. 168. 169. 170. 171.]
   [  0.   0.   0. 175. 176.   0. 178. 179.   0.]]

  [[  0. 182. 183.   0. 185. 186.   0. 188. 189.]
   [190. 191. 192. 193. 194. 195. 196. 197. 198.]
   [199. 200. 201. 202. 203. 204. 205. 206. 207.]
   [208. 209.   0. 211. 212.   0. 214. 215.   0.]]

  [[  0. 218. 219.   0. 221. 222.   0. 224. 225.]
   [226. 227. 228. 229. 230. 231. 232. 233. 234.]
   [235. 236. 237. 238. 239. 240. 241. 242. 243.]
   [244. 245.   0. 247. 248.   0. 250. 251.   0.]]

  [[  0. 254. 255.   0. 257. 258.   0.   0.   0.]
   [262. 263. 264. 265. 266. 267.   0.   0.   0.]
   [271. 272. 273. 274. 275. 276.   0.   0.   0.]
   [280. 281.   0. 283. 284.   0.   0.   0.   0.]]]]