In [96]:
import cnn
import numpy as np
import imp
imp.reload(cnn)

col1==col2
[[[[ True  True  True  True  True False  True False False]
   [ True  True  True False  True False False False False]
   [ True  True  True False  True False False False False]
   [ True  True  True False  True  True False False  True]]

  [[ True False False  True  True False  True False False]
   [False False False False  True False False False False]
   [False False False False  True False False False False]
   [False False  True False  True  True False False  True]]

  [[ True False False  True  True False  True False False]
   [False False False False  True False False False False]
   [False False False False  True False False False False]
   [False False  True False  True  True False False  True]]

  [[ True False False  True  True False  True  True  True]
   [False False False False  True False  True  True  True]
   [False False False False  True False  True  True  True]
   [False False  True False  True  True  True  True  True]]]


 [[[ True  True  True  True  True F

<module 'cnn' from '/home/qc/proj_py/cnn.py'>

In [ ]:
col1=
 [[[[  0.   0.   0.   0.   5.   6.   0.   8.   9.]
   [  0.   0.   0.  13.  14.  15.  16.  17.  18.]
   [  0.   0.   0.  22.  23.  24.  25.  26.  27.]
   [  0.   0.   0.  31.  32.   0.  34.  35.   0.]]

  [[  0.  38.  39.   0.  41.  42.   0.  44.  45.]
   [ 46.  47.  48.  49.  50.  51.  52.  53.  54.]
   [ 55.  56.  57.  58.  59.  60.  61.  62.  63.]
   [ 64.  65.   0.  67.  68.   0.  70.  71.   0.]]

  [[  0.  74.  75.   0.  77.  78.   0.  80.  81.]
   [ 82.  83.  84.  85.  86.  87.  88.  89.  90.]
   [ 91.  92.  93.  94.  95.  96.  97.  98.  99.]
   [100. 101.   0. 103. 104.   0. 106. 107.   0.]]

  [[  0. 110. 111.   0. 113. 114.   0.   0.   0.]
   [118. 119. 120. 121. 122. 123.   0.   0.   0.]
   [127. 128. 129. 130. 131. 132.   0.   0.   0.]
   [136. 137.   0. 139. 140.   0.   0.   0.   0.]]]


 [[[  0.   0.   0.   0. 149. 150.   0. 152. 153.]
   [  0.   0.   0. 157. 158. 159. 160. 161. 162.]
   [  0.   0.   0. 166. 167. 168. 169. 170. 171.]
   [  0.   0.   0. 175. 176.   0. 178. 179.   0.]]

  [[  0. 182. 183.   0. 185. 186.   0. 188. 189.]
   [190. 191. 192. 193. 194. 195. 196. 197. 198.]
   [199. 200. 201. 202. 203. 204. 205. 206. 207.]
   [208. 209.   0. 211. 212.   0. 214. 215.   0.]]

  [[  0. 218. 219.   0. 221. 222.   0. 224. 225.]
   [226. 227. 228. 229. 230. 231. 232. 233. 234.]
   [235. 236. 237. 238. 239. 240. 241. 242. 243.]
   [244. 245.   0. 247. 248.   0. 250. 251.   0.]]

  [[  0. 254. 255.   0. 257. 258.   0.   0.   0.]
   [262. 263. 264. 265. 266. 267.   0.   0.   0.]
   [271. 272. 273. 274. 275. 276.   0.   0.   0.]
   [280. 281.   0. 283. 284.   0.   0.   0.   0.]]]]

In [ ]:
d_Ai_1=
 [[[[ 9.56931853e-02 -1.32268451e-03 -1.30958159e-03  1.52681607e-03]
   [-2.15550382e-02 -6.44831331e-02 -1.31485956e-03 -7.44317204e-03]
   [-1.29368498e-03 -1.29863179e-03 -1.41218871e-02  4.82205503e-02]
   [-1.30090311e-03 -1.28666224e-03 -2.74124568e-02 -1.29785672e-03]]]


 [[[ 4.50803588e-05  4.47133949e-05 -1.47735797e-02  1.05129664e-02]
   [ 4.69973508e-05  4.64857037e-05  3.98204064e-02  4.75966134e-05]
   [ 4.50762095e-05 -1.95918239e-02 -4.63158685e-02  3.04365615e-03]
   [ 4.65783951e-05  2.68889979e-02  4.67981504e-05  4.59191995e-05]]]]