In [405]:
import cnn11
import numpy as np
import imp
imp.reload(cnn11)
# (params,params_init,g,g_d)=cnn11.init_params(lays=3)
# params=cnn11.hyperparams_test(params,params_init,g,g_d,nloop=2,lr0=2e-3,klr=0.9995,batch=64,isupdate=1,isl2grad=1)
# cnn.show(params,g)

grad.keys()= dict_keys(['d_w2', 'd_gama1', 'd_beta1', 'd_k1', 'd_gama0', 'd_beta0', 'd_k0'])
loss_check: dv= 0.0001
loss_check: yl=
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
loss_check: y1=
 [1.85218945e-04 4.78543892e-01 2.27196131e-02 4.46672819e-01
 3.43666660e-03 1.33766630e-03 4.29424152e-02 1.78566403e-04
 3.94690524e-03 3.62369036e-05]
loss_check: y2=
 [1.85123879e-04 4.78556315e-01 2.27054766e-02 4.46715187e-01
 3.43330408e-03 1.33713655e-03 4.29079626e-02 1.78571827e-04
 3.94470493e-03 3.62175516e-05]
bp: d_A1.shape bf= (1, 3, 2, 2)
bp: d_A1.shape= (1, 3, 2, 2)
bp: Y1.shape= (1, 3, 2, 2)
bp: C0.shape= (1, 2, 4, 4, 3, 3)
bp: d_Z1.shape= (1, 3, 4, 4)
bp: d_A0.shape bf= (1, 2, 4, 4)
bp: d_A0.shape= (1, 2, 4, 4)
bp: Y0.shape= (1, 2, 4, 4)
bp: C-1.shape= (1, 1, 8, 8, 3, 3)
bp: d_Z0.shape= (1, 2, 8, 8)
d_[Y0]=
 [[[-0.         -0.29351497 -0.92036474  0.03308981]
  [ 0.          0.73016928  0.62629613  0.        ]
  [ 0.         -1.41418676 -0.57703133  0.        ]
  [ 0.         -0.         

<module 'cnn11' from '/home/qc/proj_py/cnn11.py'>

In [40]:
maxpooling: z=
 [[[[-318.03187284  -36.8474868  -307.20358223  260.3859376 ]
   [   2.22158708 -547.74067978  440.63141571  467.50152235]
   [ 166.29778381  709.82006457    9.02930153  654.52863611]
   [  34.93627804  278.64563032  684.1892657   107.82792239]]

  [[ -18.89396585 -301.89200742  377.75907537  219.73415269]
   [ 344.90661606   51.32772872  200.16064834  400.82756845]
   [-108.22364957  458.34165497  527.05392114   66.42740286]
   [ 191.02181801   -4.10023376  368.28766218   62.35482279]]]]

0.6798

In [ ]:
fpdv: Z1=
 [[[ 5.23131176e+00  5.23410955e-01 -1.18534968e+00 -2.03820338e+00
   -1.10427280e+00 -2.92609391e+00 -8.10653531e-01  4.51209221e+00]
  [ 1.08569005e+00 -3.07966952e+00 -1.68669170e+00  3.46238458e-01
   -3.12345750e+00 -2.04131125e-02 -3.92029260e+00 -1.63265265e+00]
  [-1.51764117e+00  3.68583005e-02  3.88342120e+00 -3.18593090e+00
   -3.12009161e+00 -5.40824960e-02  1.60273576e+00  2.04779625e+00]
  [-1.02794464e+00  1.55842816e+00 -3.11773185e-01  5.57201154e-01
   -2.99516490e+00  1.00016737e-03  3.96198744e+00 -3.73388494e+00]
  [-2.13153680e+00 -3.98477176e-01  2.83212073e-01 -3.29913737e+00
   -4.57595824e+00  3.37892349e-01  9.83310262e-01 -4.27107489e-01]
  [-1.68007849e+00 -1.24884265e+00  1.51620119e-02 -4.26168973e-01
   -1.80106714e+00 -1.58465656e-01  2.49075552e+00 -8.77584285e-02]
  [ 1.50717045e+00 -4.85486283e-01  1.55742073e+00 -1.12144908e+00
    1.62801076e+00 -7.76426485e-01  2.45058903e-01 -7.98538556e-01]
  [ 1.88139243e+00 -1.77865126e-01  1.27261031e+00 -1.00899463e+00