In [35]:
import cnn11
import numpy as np
import imp
imp.reload(cnn11)
# (params,params_init,g,g_d)=cnn11.init_params(lays=3)
# params=cnn11.hyperparams_test(params,params_init,g,g_d,nloop=2,lr0=2e-3,klr=0.9995,batch=64,isupdate=1,isl2grad=1)
# cnn.show(params,g)

check: d_keys()=
 dict_keys(['Y2', 'X2', 'M2', 'Z2', 'Z2_2col', 'A1', 'Y1', 'X1', 'M1', 'Z1', 'Z1_2col', 'A0', 'Y0', 'X0', 'M0', 'Z0', 'Z0_2col', 'A-1'])
check: op_param= M2
check: slope=
 [[[ 0.42258685  0.67529109]
  [-1.60729877  0.50942084]]

 [[-0.26924025  0.67292121]
  [-0.16053763 -0.24314333]]

 [[ 0.17012658  0.69618749]
  [-1.13862746  0.27231339]]

 [[ 0.24534293  1.07296282]
  [ 0.16995341 -1.48825915]]]
check: grad=
 [[[ 0.42258685  0.67529109]
  [-1.60729877  0.50942084]]

 [[-0.26924025  0.67292121]
  [-0.16053763 -0.24314333]]

 [[ 0.17012658  0.69618749]
  [-1.13862746  0.27231339]]

 [[ 0.24534293  1.07296282]
  [ 0.16995341 -1.48825915]]]
check: d_keys()=
 dict_keys(['Y2', 'X2', 'M2', 'Z2', 'Z2_2col', 'A1', 'Y1', 'X1', 'M1', 'Z1', 'Z1_2col', 'A0', 'Y0', 'X0', 'M0', 'Z0', 'Z0_2col', 'A-1'])
check: op_param= Z2
check: slope=
 [[[ 0.          0.42258685  0.          0.        ]
  [ 0.          0.          0.          0.67529109]
  [ 0.          0.          0.          

<module 'cnn11' from '/home/qc/proj_py/cnn11.py'>

In [40]:
check: slope=
 [[[[ 0.42258685  0.67529109]
   [-1.60729877  0.50942084]]

  [[-0.26924025  0.67292121]
   [-0.16053763 -0.24314333]]

  [[ 0.17012657  0.69618749]
   [-1.13862746  0.27231339]]

  [[ 0.24534293  1.07296282]
   [ 0.16995341 -1.48825915]]]


 [[[ 0.05238711 -0.06060147]
   [ 0.10138622 -0.09317185]]

  [[ 0.07454762 -0.05941517]
   [-0.05816516  0.04303271]]

  [[-0.05758159  0.02448931]
   [ 0.02434874  0.00874354]]

  [[-0.12740719  0.02831051]
   [ 0.08579801  0.01329867]]]]

0.6798

In [ ]:
check: op_param= X2
check: slope=
 [[[ 1.18830914  0.0445573 ]
  [-0.19717337  0.        ]]

 [[ 0.43987529  0.43055864]
  [ 0.          0.        ]]

 [[ 0.          2.54836235]
  [-1.34898846  0.26388387]]

 [[ 0.          1.37525641]
  [ 0.         -0.10235141]]]
check: grad=
 [[[ 1.18830914  0.0445573 ]
  [-0.19717337  0.        ]]

 [[ 0.43987529  0.43055864]
  [ 0.          0.        ]]

 [[-0.          2.54836235]
  [-1.34898846  0.26388387]]

 [[ 0.          1.37525641]
  [-0.         -0.10235141]]]