In [119]:
import cnn11
import numpy as np
import imp
imp.reload(cnn11)
# (params,params_init,g,g_d)=cnn11.init_params(lays=4)
# params=cnn11.hyperparams_test(params,params_init,g,g_d,nloop=9,lr0=2e-3,klr=0.9995,batch=64,isupdate=1,isl2grad=1)
# cnn.show(params,g)

init_params: ch= [2, 4, 6, 8, 10, 10]
slope: running k0.shape= (4, 2, 3, 3)
slope: k0[1/72] slope = -2.673418457943555
slope: k0[2/72] slope = -0.028173669885944715
slope: k0[3/72] slope = 1.9218058099124133
slope: k0[4/72] slope = 2.010219963199944
slope: k0[6/72] slope = -1.3970697467335922
slope: k0[9/72] slope = -1.6738703261243157
slope: k0[12/72] slope = 5.945228534232071
slope: running gama0.shape= (4, 1, 1)
slope: gama0[1/4] slope = -11.296892581569294
slope: gama0[2/4] slope = 0.9747577648155924
slope: gama0[3/4] slope = 17.002199635385296
slope: gama0[4/4] slope = -6.6800648254705655
slope: running beta0.shape= (4, 1, 1)
slope: beta0[1/4] slope = -15.328786180246466
slope: beta0[2/4] slope = 2.499841054959262
slope: beta0[3/4] slope = 6.919298444074683
slope: beta0[4/4] slope = -9.981144878468129
slope: running k1.shape= (6, 4, 3, 3)
slope: k1[1/216] slope = 0.41268774926273005
slope: k1[2/216] slope = -0.7843394591589002
slope: k1[3/216] slope = -1.5508952753595648
slope: k1

<module 'cnn11' from '/home/qc/proj_py/cnn11.py'>

In [ ]:
grad[d_k0]=
 [[[[-2.67341846 -0.02817367  1.92180581]
   [ 2.01021996 -4.47241692 -1.39706975]
   [-5.75926484 -4.09108518 -1.67387033]]

  [[-0.16059658 -0.73663588  5.94522853]
   [ 0.89634353  4.92705358  0.06629105]
   [-2.83143515  1.04588984  1.92141909]]]


 [[[-2.08950702 -1.45191267 -0.05648671]
   [ 2.77451742  0.75730007  2.46674656]
   [ 0.02237073 -1.31900957  1.38712687]]

  [[ 2.51118127 -1.76096994 -1.05255664]
   [ 3.15476679 -5.8902709   1.26638009]
   [-1.07766478 -5.90737727 -0.07173173]]]


 [[[-1.64564716 -5.72660297 -0.10937285]
   [-5.00796993 -4.47274603 -3.52455183]
   [-1.34181544  2.65060491  1.01756644]]

In [117]:
import cnn11
import numpy as np
import imp
imp.reload(cnn11)
# (params,params_init,g,g_d)=cnn11.init_params(lays=4)
# params=cnn11.hyperparams_test(params,params_init,g,g_d,nloop=9,lr0=2e-3,klr=0.9995,batch=64,isupdate=1,isl2grad=1)
# cnn.show(params,g)

init_params: ch= [1, 3, 5, 7, 9, 10]
slope: running k0.shape= (3, 1, 3, 3)
slope: k0[1/27] slope = 0.9738372124701299
slope: k0[2/27] slope = 3.8210586378539797
slope: k0[3/27] slope = 1.5296045170032355
slope: k0[4/27] slope = 1.2533018040272736
slope: k0[6/27] slope = 1.8336332985313673
slope: k0[9/27] slope = -14.199453643470859
slope: k0[12/27] slope = 5.709518508822952
slope: running gama0.shape= (3, 1, 1)
slope: gama0[1/3] slope = -3.561856336631308
slope: gama0[2/3] slope = 10.566412203161235
slope: gama0[3/3] slope = -7.004555895306907
slope: running beta0.shape= (3, 1, 1)
slope: beta0[1/3] slope = -7.660642482676393
slope: beta0[2/3] slope = 10.765533384926584
slope: beta0[3/3] slope = 17.80642783977271
slope: running k1.shape= (5, 3, 3, 3)
slope: k1[1/135] slope = 0.04682051013560339
slope: k1[2/135] slope = -0.04565920299626213
slope: k1[3/135] slope = -2.047869021026827
slope: k1[4/135] slope = -3.830087209522048
slope: k1[6/135] slope = -3.392719683859013
slope: k1[9/135] 

<module 'cnn11' from '/home/qc/proj_py/cnn11.py'>

In [ ]:
slope[d_k0]=
 [[[  0.97383721   3.82105864   1.52960452]
  [  1.2533018   -2.97365739   1.8336333 ]
  [ -1.32979308   2.70423146 -14.19945364]]

 [[ -1.93233544  -9.84000907   5.70951851]
  [ -5.43803353 -14.94498091  12.28556841]
  [-11.07388765  -2.48748562  -8.8860284 ]]

 [[  5.92660189  -1.38259127  -2.23507591]
  [  9.62656337   0.04774316  -4.04622151]
  [ -8.29735166  -0.30203304   6.88245668]]]