In [51]:
import cnn11
import numpy as np
import imp
imp.reload(cnn11)
# (params,params_init,g,g_d)=cnn11.init_params(lays=3)
# params=cnn11.hyperparams_test(params,params_init,g,g_d,nloop=2,lr0=2e-3,klr=0.9995,batch=64,isupdate=1,isl2grad=1)
# cnn.show(params,g)

bp: d_A1.shape bf= (5, 3, 8, 8)
bp: d_A1.shape= (5, 3, 8, 8)
bp: Y1.shape= (5, 3, 8, 8)
bp: C0.shape= (5, 2, 8, 8, 3, 3)
bp: d_Z1.shape= (5, 3, 8, 8)
bp: d_A0.shape bf= (5, 2, 8, 8)
bp: d_A0.shape= (5, 2, 8, 8)
bp: Y0.shape= (5, 2, 8, 8)
bp: C-1.shape= (5, 1, 8, 8, 3, 3)
bp: d_Z0.shape= (5, 2, 8, 8)
slope: running k0.shape= (2, 1, 3, 3)
slope: k0[1/18] slope = -1.9077794354060982
slope: k0[2/18] slope = -0.25770650786682836
slope: k0[3/18] slope = -1.5393646199512998
slope: k0[4/18] slope = -0.2831197804198382
slope: k0[6/18] slope = -1.1802587790654684
slope: k0[9/18] slope = 1.399976102067768
slope: k0[12/18] slope = -1.6975684077991102
slope: running gama0.shape= (2, 1, 1)
slope: gama0[1/2] slope = -2.2318392039366586
slope: gama0[2/2] slope = 2.2318392243647622
slope: running beta0.shape= (2, 1, 1)
slope: beta0[1/2] slope = 2.9052527593442785
slope: beta0[2/2] slope = -0.7538316918243025
slope: running k1.shape= (3, 2, 3, 3)
slope: k1[1/54] slope = -0.8330530541833524
slope: k1[2/5

<module 'cnn11' from '/home/qc/proj_py/cnn11.py'>

In [ ]:
grad[d_k1]=
 [[[[-0.07740564 -1.1172668   0.59112684]
   [-0.06254214  0.03765534 -0.09994058]
   [ 1.25947753  0.64493471 -0.07456369]]

  [[-0.17064479 -0.74598944 -0.23099862]
   [ 1.54257733 -0.34714144 -0.27958185]
   [ 0.17859669  0.12705746  0.56851662]]]
  
slope[d_k1]=
 [[[[-0.07740564 -1.1172668   0.59112684]
   [-0.06254214  0.03765534 -0.09994058]
   [ 1.25947753  0.64493471 -0.07456369]]

  [[-0.17064479 -0.74598944 -0.23099862]
   [ 1.54257733 -0.34714144 -0.27958185]
   [ 0.17859669  0.12705746  0.56851662]]]


 [[[-0.25037488  1.14657118  0.19290091]
   [ 0.22435386  0.45177758  0.27273919]
   [-0.1094737   0.2306238  -0.12036815]]