In [994]:
import cnn11
import numpy as np
import imp
imp.reload(cnn11)
# (params,params_init,g,g_d)=cnn11.init_params(lays=3)
# params=cnn11.hyperparams_test(params,params_init,g,g_d,nloop=2,lr0=2e-3,klr=0.9995,batch=64,isupdate=1,isl2grad=1)
# cnn.show(params,g)

fp: M0.shape= (1, 2, 4, 4)
fp: ZdM0.shape= (1, 2, 4, 4, 2, 2)
fpdv: M0=
 [[[ 0.01851575  0.06943774  0.03161893  0.01449672]
  [ 0.05624322  0.08595533 -0.00980472 -0.01450575]
  [-0.01224181  0.06439104 -0.02611601  0.06344181]
  [-0.01511631  0.00827715  0.00799466  0.04515869]]

 [[ 0.04700663  0.03443989  0.03620348  0.00395372]
  [ 0.02915512  0.03374579 -0.00274648 -0.00473441]
  [ 0.01097011  0.00821139  0.0043613   0.01261584]
  [ 0.00212576  0.00337449  0.01683633  0.00384019]]]
fpdv: ZdM0=
 [[[[[0. 0.]
    [0. 0.]]

   [[0. 0.]
    [1. 0.]]

   [[1. 0.]
    [0. 0.]]

   [[1. 0.]
    [0. 0.]]]


  [[[0. 1.]
    [0. 0.]]

   [[1. 0.]
    [0. 0.]]

   [[0. 0.]
    [1. 0.]]

   [[0. 0.]
    [0. 1.]]]


  [[[0. 0.]
    [0. 1.]]

   [[0. 1.]
    [0. 0.]]

   [[0. 0.]
    [1. 0.]]

   [[0. 0.]
    [1. 0.]]]


  [[[0. 0.]
    [1. 0.]]

   [[0. 0.]
    [1. 0.]]

   [[0. 0.]
    [1. 0.]]

   [[0. 0.]
    [0. 0.]]]]



 [[[[0. 0.]
    [0. 1.]]

   [[0. 0.]
    [1. 0.]]

   [[1. 0.]
    

<module 'cnn11' from '/home/qc/proj_py/cnn11.py'>

In [40]:
fpdv: M0=
 [[[ 0.01851575  0.06943774  0.03161893  0.01449672]
  [ 0.05624322  0.08595533 -0.00980472 -0.01450575]
  [-0.01224181  0.06439104 -0.02611601  0.06344181]
  [-0.01511631  0.00827715  0.00799466  0.04515869]]

 [[ 0.04700663  0.03443989  0.03620348  0.00395372]
  [ 0.02915512  0.03374579 -0.00274648 -0.00473441]
  [ 0.01097011  0.00821139  0.0043613   0.01261584]
  [ 0.00212576  0.00337449  0.01683633  0.00384019]]]

0.6798

In [ ]:
fpdv: Z1=
 [[[ 5.23131176e+00  5.23410955e-01 -1.18534968e+00 -2.03820338e+00
   -1.10427280e+00 -2.92609391e+00 -8.10653531e-01  4.51209221e+00]
  [ 1.08569005e+00 -3.07966952e+00 -1.68669170e+00  3.46238458e-01
   -3.12345750e+00 -2.04131125e-02 -3.92029260e+00 -1.63265265e+00]
  [-1.51764117e+00  3.68583005e-02  3.88342120e+00 -3.18593090e+00
   -3.12009161e+00 -5.40824960e-02  1.60273576e+00  2.04779625e+00]
  [-1.02794464e+00  1.55842816e+00 -3.11773185e-01  5.57201154e-01
   -2.99516490e+00  1.00016737e-03  3.96198744e+00 -3.73388494e+00]
  [-2.13153680e+00 -3.98477176e-01  2.83212073e-01 -3.29913737e+00
   -4.57595824e+00  3.37892349e-01  9.83310262e-01 -4.27107489e-01]
  [-1.68007849e+00 -1.24884265e+00  1.51620119e-02 -4.26168973e-01
   -1.80106714e+00 -1.58465656e-01  2.49075552e+00 -8.77584285e-02]
  [ 1.50717045e+00 -4.85486283e-01  1.55742073e+00 -1.12144908e+00
    1.62801076e+00 -7.76426485e-01  2.45058903e-01 -7.98538556e-01]
  [ 1.88139243e+00 -1.77865126e-01  1.27261031e+00 -1.00899463e+00