In [139]:
import numpy as np
(h,w,kf)=(13,8,7)
a=np.arange(1*h*w*1).reshape(h,w,1)+1
print('before padding :a.shape=',a.shape)
# a=np.pad(a,1)
p=int(kf/2)
ap=np.pad(a,((p,p),(p,p),(0,0)))
# ap=a
print('after padding : ap.shape=',ap.shape)
# print('ap=\n',ap)
print('ap=\n',ap.transpose(2,0,1))
(hp,wp,Non)=ap.shape
(cols_r,cols_c)=(hp-kf+1,wp-kf+1)
cols=np.zeros((cols_r,cols_c,kf*kf))
for r in range(cols_r) :
    for c in range(cols_c) :
        cols[r,c,:]=ap[r:r+kf,c:c+kf, 0].reshape(-1)
        

# b=np.zeros(ap.shape)        
b=np.zeros(a.shape)    
for r in range(cols.shape[0]):
    for c in range(cols.shape[1]):
#             b[r,c]=cols[r,c,0]
            b[r,c]=cols[r,c,int(kf*(p+0.5))]

            
# a=a[p:-p,p:-p]   
# b=b[p:-p,p:-p]   
# cols=cols[int(p/2+0.5):-int(p/2+0.5),int(p/2+0.5):-int(p/2+0.5)]   
# print('cols.shape=',cols.shape)
print('a=\n',a.transpose(2,0,1))
print('b=\n',b.transpose(2,0,1))     
print('cols=\n',cols)       
print('cols.shape=',cols.shape)
print('ap.shape=',ap.shape)
print('a.shape=',a.shape)
print('b.shape=',b.shape)
# print('cols[0]=\n',cols[0])      


before padding :a.shape= (13, 8, 1)
after padding : ap.shape= (19, 14, 1)
ap=
 [[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   1   2   3   4   5   6   7   8   0   0   0]
  [  0   0   0   9  10  11  12  13  14  15  16   0   0   0]
  [  0   0   0  17  18  19  20  21  22  23  24   0   0   0]
  [  0   0   0  25  26  27  28  29  30  31  32   0   0   0]
  [  0   0   0  33  34  35  36  37  38  39  40   0   0   0]
  [  0   0   0  41  42  43  44  45  46  47  48   0   0   0]
  [  0   0   0  49  50  51  52  53  54  55  56   0   0   0]
  [  0   0   0  57  58  59  60  61  62  63  64   0   0   0]
  [  0   0   0  65  66  67  68  69  70  71  72   0   0   0]
  [  0   0   0  73  74  75  76  77  78  79  80   0   0   0]
  [  0   0   0  81  82  83  84  85  86  87  88   0   0   0]
  [  0   0   0  89  90  91  92  93  94  95  96   0   0   0]
  [  0   0   0  97  9