In [1]:
import numpy as np

In [257]:
n=2
a1=np.arange(n*3*1).reshape(n,3)+1
# b1=np.ones((3,4),dtype=int)
b1 =np.array([[1,1,1,1],[0,0,0,0],[1,1,1,1]])
print('a1 shape:',a1.shape)
print(a1)
print('b1 shape:',b1.shape)
print(b1)

a1 shape: (2, 3)
[[1 2 3]
 [4 5 6]]
b1 shape: (3, 4)
[[1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]]


In [254]:
aa1=np.einsum('ij,jl->ijl',a1,b1)
print(aa1)
aa1.shape

[[[1 1 1 1]
  [0 0 0 0]
  [3 3 3 3]]

 [[4 4 4 4]
  [0 0 0 0]
  [6 6 6 6]]

 [[7 7 7 7]
  [0 0 0 0]
  [9 9 9 9]]]


(3, 3, 4)

In [256]:
aa3=np.einsum('ij,jl->ij',a1,b1)
print(aa3)
aa3.shape

[[ 4  0 12]
 [16  0 24]
 [28  0 36]]


(3, 3)

In [285]:
aa2=np.einsum('ij,lk->ijkl',a1,b1)
# aa2=np.einsum('ij,kl->ijkl',a1,b1)
print(aa2.shape)
print(aa2)

(2, 3, 4, 3)
[[[[1 0 1]
   [1 0 1]
   [1 0 1]
   [1 0 1]]

  [[2 0 2]
   [2 0 2]
   [2 0 2]
   [2 0 2]]

  [[3 0 3]
   [3 0 3]
   [3 0 3]
   [3 0 3]]]


 [[[4 0 4]
   [4 0 4]
   [4 0 4]
   [4 0 4]]

  [[5 0 5]
   [5 0 5]
   [5 0 5]
   [5 0 5]]

  [[6 0 6]
   [6 0 6]
   [6 0 6]
   [6 0 6]]]]


In [165]:
c1=np.einsum('ij,kl->ijkl',a1,b1)
print(c1)
c1.shape

[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[2. 2. 2. 2.]
   [2. 2. 2. 2.]
   [2. 2. 2. 2.]]]


 [[[3. 3. 3. 3.]
   [3. 3. 3. 3.]
   [3. 3. 3. 3.]]

  [[4. 4. 4. 4.]
   [4. 4. 4. 4.]
   [4. 4. 4. 4.]]

  [[5. 5. 5. 5.]
   [5. 5. 5. 5.]
   [5. 5. 5. 5.]]]]


(2, 3, 3, 4)

In [141]:
d1=np.einsum('ij,kl->ijkl',b1,a1)
print(d1)
d1.shape

[[[[0. 1. 2.]
   [3. 4. 5.]]

  [[0. 1. 2.]
   [3. 4. 5.]]

  [[0. 1. 2.]
   [3. 4. 5.]]

  [[0. 1. 2.]
   [3. 4. 5.]]]


 [[[0. 1. 2.]
   [3. 4. 5.]]

  [[0. 1. 2.]
   [3. 4. 5.]]

  [[0. 1. 2.]
   [3. 4. 5.]]

  [[0. 1. 2.]
   [3. 4. 5.]]]


 [[[0. 1. 2.]
   [3. 4. 5.]]

  [[0. 1. 2.]
   [3. 4. 5.]]

  [[0. 1. 2.]
   [3. 4. 5.]]

  [[0. 1. 2.]
   [3. 4. 5.]]]


 [[[0. 1. 2.]
   [3. 4. 5.]]

  [[0. 1. 2.]
   [3. 4. 5.]]

  [[0. 1. 2.]
   [3. 4. 5.]]

  [[0. 1. 2.]
   [3. 4. 5.]]]


 [[[0. 1. 2.]
   [3. 4. 5.]]

  [[0. 1. 2.]
   [3. 4. 5.]]

  [[0. 1. 2.]
   [3. 4. 5.]]

  [[0. 1. 2.]
   [3. 4. 5.]]]]


(5, 4, 2, 3)

In [136]:
e1=np.einsum('ij,kl->jkl',b1,a1)
print(e1)
e1.shape

[[[ 0.  3.  6.]
  [ 9. 12. 15.]]

 [[ 0.  3.  6.]
  [ 9. 12. 15.]]

 [[ 0.  3.  6.]
  [ 9. 12. 15.]]

 [[ 0.  3.  6.]
  [ 9. 12. 15.]]

 [[ 0.  3.  6.]
  [ 9. 12. 15.]]]


(5, 2, 3)