In [17]:
import grad_test
import numpy as np
import imp
imp.reload(grad_test)

u= [[[0.007]]

 [[0.022]]]
v= [[[1.86666667e-05]]

 [[1.86666667e-05]]]
z=
 [[[0.    0.001 0.002]
  [0.003 0.004 0.005]
  [0.006 0.007 0.008]
  [0.009 0.01  0.011]
  [0.012 0.013 0.014]]

 [[0.015 0.016 0.017]
  [0.018 0.019 0.02 ]
  [0.021 0.022 0.023]
  [0.024 0.025 0.026]
  [0.027 0.028 0.029]]]
x=
 [[[-1.61975137e+00 -1.38835832e+00 -1.15696526e+00]
  [-9.25572212e-01 -6.94179159e-01 -4.62786106e-01]
  [-2.31393053e-01  0.00000000e+00  2.31393053e-01]
  [ 4.62786106e-01  6.94179159e-01  9.25572212e-01]
  [ 1.15696526e+00  1.38835832e+00  1.61975137e+00]]

 [[-1.61975137e+00 -1.38835832e+00 -1.15696526e+00]
  [-9.25572212e-01 -6.94179159e-01 -4.62786106e-01]
  [-2.31393053e-01 -8.02805922e-16  2.31393053e-01]
  [ 4.62786106e-01  6.94179159e-01  9.25572212e-01]
  [ 1.15696526e+00  1.38835832e+00  1.61975137e+00]]]
xx=
 [[[[ 2.62359450e+00  2.24879529e+00  1.87399607e+00]
   [ 1.49919686e+00  1.12439764e+00  7.49598429e-01]
   [ 3.74799215e-01  1.30034599e-15 -3.74799215e-01]
   [-7.4

<module 'grad_test' from '/home/qc/proj_py/grad_test.py'>