In [23]:
import cnn
import numpy as np
import imp
imp.reload(cnn)
# (params,params_init,g,g_d)=cnn.init_params(lays=2)
# params=cnn.hyperparams_test(params,params_init,g,g_d,nloop=4,lr0=2e-3,klr=0.9995,batch=64,isupdate=1,isl2grad=1)
# cnn.show(params,g)

params: ch= [1, 2, 3, 4, 10]
params: lays= 4
params: k0.shape= (2, 1, 3, 3)
params: gama0.shape= (2, 1, 1)
params: beta0.shape= (2, 1, 1)
params: k1.shape= (3, 2, 3, 3)
params: gama1.shape= (3, 1, 1)
params: beta1.shape= (3, 1, 1)
params: k2.shape= (4, 3, 3, 3)
params: gama2.shape= (4, 1, 1)
params: beta2.shape= (4, 1, 1)
params: w3.shape= (10, 4, 5, 6)
x.shape= (2, 1, 5, 6)
bp: gamai2.shape= (4, 1, 1)
bp: d_Yi2.shape= (2, 4, 5, 6)
bp: d_Xi2.shape= (2, 4, 5, 6)
bp: k2.shape= (4, 3, 3, 3)
bp: k2_fl.shape= (4, 3, 3, 3)
bp: gamai1.shape= (3, 1, 1)
bp: d_Yi1.shape= (2, 3, 5, 6)
bp: d_Xi1.shape= (2, 3, 5, 6)
bp: k1.shape= (3, 2, 3, 3)
bp: k1_fl.shape= (3, 2, 3, 3)
bp: gamai0.shape= (2, 1, 1)
bp: d_Yi0.shape= (2, 2, 5, 6)
bp: d_Xi0.shape= (2, 2, 5, 6)
bp: k0.shape= (2, 1, 3, 3)
bp: k0_fl.shape= (2, 1, 3, 3)
x=
 [[[ 0.01624345 -0.00611756 -0.00528172 -0.01072969  0.00865408
   -0.02301539]
  [ 0.01744812 -0.00761207  0.00319039 -0.0024937   0.01462108
   -0.02060141]
  [-0.00322417 -0.0038405

<module 'cnn' from '/home/qc/proj_py/cnn.py'>

In [8]:
grad[d_k1]=
 [[[[-0.99016061 -0.16467183  0.85280805]
   [-0.0248142   0.80279729 -0.18327345]
   [ 0.9521527   0.1054236   0.01484696]]

  [[-0.09330691  0.69446051  0.44473749]
   [ 0.2168337  -0.34839465 -0.99780093]
   [ 1.45750833  0.28772786 -0.07465494]]]

params: ch= [1, 2, 3, 4, 10]
params: k0.shape= (2, 1, 3, 3)
params: gama0.shape= (2, 1, 1)
params: beta0.shape= (2, 1, 1)
params: k1.shape= (3, 2, 3, 3)
params: gama1.shape= (3, 1, 1)
params: beta1.shape= (3, 1, 1)
params: k2.shape= (4, 3, 3, 3)
params: gama2.shape= (4, 1, 1)
params: beta2.shape= (4, 1, 1)
params: w3.shape= (10, 4, 5, 6)
params: gama3.shape= (10, 1, 1)
params: beta3.shape= (10, 1, 1)
x.shape= (2, 1, 5, 6)
cross_entropy
fp: Y.shape= (2, 10, 1, 1)
Y.shape= (2, 10, 1, 1)
Y=
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
YL=
 [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


<module 'cnn' from '/home/qc/proj_py/cnn.py'>