In [19]:
import numpy as np
a1=np.arange(3*2*2).reshape(3,2,2)+1
b1=(a1-a1.max((-2,-1),keepdims=1)+1)
c1=b1.copy()
c1[b1<1]=0

print('a1=\n',a1)
print('b1=\n',b1)
print('c1=\n',c1)
print('a1.shape=',a1.shape)
print('b1.shape=',b1.shape)

a1=
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
b1=
 [[[-2 -1]
  [ 0  1]]

 [[-2 -1]
  [ 0  1]]

 [[-2 -1]
  [ 0  1]]]
c1=
 [[[0 0]
  [0 1]]

 [[0 0]
  [0 1]]

 [[0 0]
  [0 1]]]
a1.shape= (3, 2, 2)
b1.shape= (3, 2, 2)


In [22]:
import numpy as np
a1=np.arange(3*2*2).reshape(3,2,2)+1
b1=(a1+1-a1.max((-2,-1),keepdims=1))
# c1=b1.copy()
b1[b1<1]=0

print('a1=\n',a1)
print('b1=\n',b1)
# print('c1=\n',c1)
print('a1.shape=',a1.shape)
print('b1.shape=',b1.shape)

a1=
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
b1=
 [[[0 0]
  [0 1]]

 [[0 0]
  [0 1]]

 [[0 0]
  [0 1]]]
a1.shape= (3, 2, 2)
b1.shape= (3, 2, 2)


In [ ]:
a2=
 [[[[ 0  0  0  0  0  0]
   [ 0  1  2  3  4  0]
   [ 0  5  6  7  8  0]
   [ 0  9 10 11 12  0]
   [ 0 13 14 15 16  0]
   [ 0  0  0  0  0  0]]

  [[ 0  0  0  0  0  0]
   [ 0 17 18 19 20  0]
   [ 0 21 22 23 24  0]
   [ 0 25 26 27 28  0]
   [ 0 29 30 31 32  0]
   [ 0  0  0  0  0  0]]]]