In [1]:
import numpy as np

In [57]:
a1=np.arange(2*2*2).reshape(2,2,2)
b1=np.arange(2*2*2).reshape(2,2,2)
# np.sqrt(a1)
a1

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [63]:
np.max(a1)

7

In [62]:
c1=np.where(a1==np.max(a1)) 
c1

(array([1]), array([1]), array([1]))

In [71]:
c1=np.where(a1==3) 
c1
# np.squeeze(c1)

(array([0]), array([1]), array([1]))

In [80]:
a1=np.random.randn(3,6,1)
a1

array([[[-0.95464935],
        [-0.86855607],
        [-1.17893517],
        [-2.46958949],
        [ 0.31272908],
        [ 0.02163794]],

       [[ 0.51423974],
        [-0.7738582 ],
        [-2.09798212],
        [ 1.37425338],
        [-1.77674902],
        [ 0.27782736]],

       [[-0.03341532],
        [ 0.44036294],
        [-1.5156224 ],
        [ 0.20518197],
        [-0.6846249 ],
        [-0.2908424 ]]])

In [81]:
d1=np.argmax(a1)
d1

9