In [9]:
import numpy as np
a=np.ones((5,3))
print('a.shape=',a.shape)
# print('a=\n',a)
b=np.arange(2*3*4*1).reshape(2,3,4,1)
print('b.shape=',b.shape)
print('b=\n',b)
c=np.einsum('ij,mjkn->mikn',a,b)
print('c.shape=',c.shape)
print('c=\n',c)


a.shape= (5, 3)
b.shape= (2, 3, 4, 1)
b=
 [[[[ 0]
   [ 1]
   [ 2]
   [ 3]]

  [[ 4]
   [ 5]
   [ 6]
   [ 7]]

  [[ 8]
   [ 9]
   [10]
   [11]]]


 [[[12]
   [13]
   [14]
   [15]]

  [[16]
   [17]
   [18]
   [19]]

  [[20]
   [21]
   [22]
   [23]]]]


ValueError: einstein sum subscripts string includes output subscript 'n' multiple times

In [1]:
import numpy as np
# a=np.arange(2*3).reshape(2,3)+1
# a=np.ones((2,3))
a=np.ones((2,3,4))
# a=np.array(1.0)
print('a=\n',a)
print('a.shape=',a.shape)
b=[]
# b=np.array(b)
# for i in a:
for i in np.nditer(a,op_flags=['readwrite']):    
#     b.append(i*3)
#     i[...]+=1
    i+=1
    
#     tt=i*1
#     tt=i
#     b.append(tt)
#     i[...]=1.5
#     print('i=',i)
# b=np.array(b)
# b=b.reshape((a.shape))
print('a=\n',a)
print('b=\n',b)

a=
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
a.shape= (2, 3, 4)
a=
 [[[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]]


In [7]:
import numpy as np
a=np.ones((2,3,4,5,6))
# print('a=\n',a)
print('a.shape=',a.shape)
# b=a[1,...,4]
b=a[1,1,:,...,4]
print('bshape=',b.shape)

a.shape= (2, 3, 4, 5, 6)
bshape= (4, 5)
