In [26]:
import numpy as np
from skimage.util import view_as_windows as vw
(ba,hi,wi)=(2,4,4)
a1=np.arange(ba*hi*wi,dtype=np.uint8).reshape(ba,hi,wi)
# a1=np.arange(hi*wi,dtype=np.uint8).reshape(hi,wi)+1
# b1=vw(a1,(3,3))
b1=vw(a1,(1,3,3))
# b1=b1.reshape(ba,hi,wi)
print('a1=\n',a1)
print('b1=\n',b1)
print('a1.shape=',a1.shape)
print('b1.shape=',b1.shape)
# viewW(A, (BSZ[0],BSZ[1])).reshape(-1,BSZ[0]*BSZ[1]).T[:,::stepsize]
# b1=

a1=
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]
b1=
 [[[[[[ 0  1  2]
     [ 4  5  6]
     [ 8  9 10]]]


   [[[ 1  2  3]
     [ 5  6  7]
     [ 9 10 11]]]]



  [[[[ 4  5  6]
     [ 8  9 10]
     [12 13 14]]]


   [[[ 5  6  7]
     [ 9 10 11]
     [13 14 15]]]]]




 [[[[[16 17 18]
     [20 21 22]
     [24 25 26]]]


   [[[17 18 19]
     [21 22 23]
     [25 26 27]]]]



  [[[[20 21 22]
     [24 25 26]
     [28 29 30]]]


   [[[21 22 23]
     [25 26 27]
     [29 30 31]]]]]]
a1.shape= (2, 4, 4)
b1.shape= (2, 2, 2, 1, 3, 3)
