In [358]:
import numpy as np
mm=3;rr=3;cc=3
a1=np.arange(mm*rr*cc).reshape(mm,rr,cc)
b1=np.ones((3,3,3))
# o1=np.ones((3,1))
# b2=np.array([o1,o1*3,o1*21])
print('a1.shape=',a1.shape)
print('b1.shape=',b1.shape)
print('a1=')
print(a1)
print('b1=')
print(b1)

a1.shape= (3, 3, 3)
b1.shape= (3, 3, 3)
a1=
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
b1=
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [32]:
import numpy as np
a1=np.arange(2*3*4).reshape(2,3,4)+2
print('a1=\n',a1)
b1=np.mean(a1,axis=(1,2))
c1=np.mean(a1,axis=(1,2),keepdims=1)
# b1=np.mean(np.mean(a1,axis=1),axis=1)
print('b1=\n',b1)
print('c1=\n',c1)
print('b1.shape=',b1.shape)
print('c1.shape=',c1.shape)
print('a1.shape=',a1.shape)
a1.shape[1:3]

a1=
 [[[ 2  3  4  5]
  [ 6  7  8  9]
  [10 11 12 13]]

 [[14 15 16 17]
  [18 19 20 21]
  [22 23 24 25]]]
b1=
 [ 7.5 19.5]
c1=
 [[[ 7.5]]

 [[19.5]]]
b1.shape= (2,)
c1.shape= (2, 1, 1)
a1.shape= (2, 3, 4)


(3, 4)

In [60]:
import numpy as np
a1=np.arange(2*3*4).reshape(2,3,4)
print('a1=\n',a1)
# b1=np.pad(a1,((1,1),()))
# b1=np.pad( a1 , pad_width=((1,1),(1,1)) )
# b1=np.pad( a1 , ((0,0),(1,1),(1,1)) )
b1=np.pad( a1 , ((0,0),(1,1),(1,1)) )
print('b1=\n',b1)

a1=
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
b1=
 [[[ 0  0  0  0  0  0]
  [ 0  0  1  2  3  0]
  [ 0  4  5  6  7  0]
  [ 0  8  9 10 11  0]
  [ 0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0]
  [ 0 12 13 14 15  0]
  [ 0 16 17 18 19  0]
  [ 0 20 21 22 23  0]
  [ 0  0  0  0  0  0]]]
