In [7]:
import numpy as np
import mnist
import copy
from matplotlib import pyplot as plt 
import pickle
import sys
import time


In [1]:
import tensorflow as tf
tf.__version__

'2.4.1'

In [6]:
import numpy as np
a1=np.arange(2*3*4).reshape(2,3,4)
print('a1.shape=',a1.shape)
print('a1=\n',a1)
# k1=np.arange(1*1*3).reshape(1,3)
k1=np.arange(1*1*3)
print('k1.shape=',k1.shape)
print('k1=\n',k1)
b1=k1@a1
print('b1.shape=',b1.shape)
print('b1=\n',b1)


a1.shape= (2, 3, 4)
a1=
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
k1.shape= (3,)
k1=
 [0 1 2]
b1.shape= (2, 4)
b1=
 [[20 23 26 29]
 [56 59 62 65]]


In [16]:
import  pandas as pd
pd.set_option('max_columns',None)
pd.set_option('max_row',None)


In [13]:
import numpy as np
a1=np.arange(2*4*6).reshape(2,4,6)
print('a1=\n',a1)
b1=np.max(a1,axis=1)
print('b1=\n',b1)
print('b1.shape=',b1.shape)



a1=
 [[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[24 25 26 27 28 29]
  [30 31 32 33 34 35]
  [36 37 38 39 40 41]
  [42 43 44 45 46 47]]]
b1=
 [[18 19 20 21 22 23]
 [42 43 44 45 46 47]]
b1.shape= (2, 6)
