In [7]:
import numpy as np
import mnist
import copy
from matplotlib import pyplot as plt 
import pickle
import sys
import time


In [3]:
import numpy as np
a1=np.arange(2*3*4).reshape(2,3,4)
print('a1.shape=',a1.shape)
print('a1=\n',a1)
b1=a1[:,0:3,0:3]
print('b1.shape=',b1.shape)
print('b1=\n',b1)


a1.shape= (2, 3, 4)
a1=
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
b1.shape= (2, 3, 3)
b1=
 [[[ 0  1  2]
  [ 4  5  6]
  [ 8  9 10]]

 [[12 13 14]
  [16 17 18]
  [20 21 22]]]


In [6]:
import numpy as np
a1=np.arange(2*2*1*2).reshape(2,2,1,2)
print('a1.shape=',a1.shape)
print('a1=\n',a1)
a1=np.squeeze(a1)
# print('b1.shape=',b1.shape)
# print('b1=\n',b1)
print('a1.shape=',a1.shape)
print('a1=\n',a1)


a1.shape= (2, 2, 1, 2)
a1=
 [[[[0 1]]

  [[2 3]]]


 [[[4 5]]

  [[6 7]]]]
a1.shape= (2, 2, 2)
a1=
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [16]:
import  pandas as pd
pd.set_option('max_columns',None)
pd.set_option('max_row',None)


In [7]:
import numpy as np
a1=np.arange(2e4).reshape(-1,1)
# print('a1=\n',a1)
b1=a1@a1.T
# print('b1=\n',b1)
print('b1.shape=',b1.shape)



b1.shape= (20000, 20000)
