In [16]:
import test
import numpy as np
import imp
imp.reload(test)

u= 0.00375
v= 7.437500000000001e-06
z=
 [[0.    0.001]
 [0.002 0.003]
 [0.004 0.005]
 [0.006 0.007]]
x=
 [[-1.52607252 -1.0900518 ]
 [-0.65403108 -0.21801036]
 [ 0.21801036  0.65403108]
 [ 1.0900518   1.52607252]]
xx=
 [[[[ 2.32889734  1.6634981 ]
   [ 0.99809886  0.33269962]
   [-0.33269962 -0.99809886]
   [-1.6634981  -2.32889734]]

  [[ 1.6634981   1.18821293]
   [ 0.71292776  0.23764259]
   [-0.23764259 -0.71292776]
   [-1.18821293 -1.6634981 ]]]


 [[[ 0.99809886  0.71292776]
   [ 0.42775665  0.14258555]
   [-0.14258555 -0.42775665]
   [-0.71292776 -0.99809886]]

  [[ 0.33269962  0.23764259]
   [ 0.14258555  0.04752852]
   [-0.04752852 -0.14258555]
   [-0.23764259 -0.33269962]]]


 [[[-0.33269962 -0.23764259]
   [-0.14258555 -0.04752852]
   [ 0.04752852  0.14258555]
   [ 0.23764259  0.33269962]]

  [[-0.99809886 -0.71292776]
   [-0.42775665 -0.14258555]
   [ 0.14258555  0.42775665]
   [ 0.71292776  0.99809886]]]


 [[[-1.6634981  -1.18821293]
   [-0.71292776 -0.23764259]
   [ 0.23

<module 'test' from '/home/qc/proj_py/test.py'>

In [66]:
test.grad

array([[[[ 270.44292336],
         [-355.28776207],
         [ -90.14764112],
         [ 174.99247982]]],


       [[[-355.28776207],
         [ 623.96308462],
         [-178.52768144],
         [ -90.14764112]]],


       [[[ -90.14764112],
         [-178.52768144],
         [ 623.96308462],
         [-355.28776207]]],


       [[[ 174.99247982],
         [ -90.14764112],
         [-355.28776207],
         [ 270.44292336]]]])

In [67]:
test.mnE

array([[[[4.],
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [4.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [4.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         [4.]]]])

In [68]:
test.xx

array([[[[ 1.78571429],
         [ 0.5952381 ],
         [-0.5952381 ],
         [-1.78571429]]],


       [[[ 0.5952381 ],
         [ 0.1984127 ],
         [-0.1984127 ],
         [-0.5952381 ]]],


       [[[-0.5952381 ],
         [-0.1984127 ],
         [ 0.1984127 ],
         [ 0.5952381 ]]],


       [[[-1.78571429],
         [-0.5952381 ],
         [ 0.5952381 ],
         [ 1.78571429]]]])

In [70]:
np.outer(test.x,test.x)

array([[ 1.78571429,  0.5952381 , -0.5952381 , -1.78571429],
       [ 0.5952381 ,  0.1984127 , -0.1984127 , -0.5952381 ],
       [-0.5952381 , -0.1984127 ,  0.1984127 ,  0.5952381 ],
       [-1.78571429, -0.5952381 ,  0.5952381 ,  1.78571429]])