In [73]:
import numpy as np
a1=np.arange(4*5*3).reshape(4,5,3)
print('a1.shape=',a1.shape)
print('a1=\n',a1)
x1=np.arange(2)
x2=np.array([2,1])
# b1=a1[x1,x2,:]
# b1=a1[x2,x2,:]
b1=a1[0:1,x2,:]
print('b1.shape=',b1.shape)
print('b1=\n',b1)
# print('x.shape=',a1[:,0:4,:].shape)

a1.shape= (4, 5, 3)
a1=
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]

 [[45 46 47]
  [48 49 50]
  [51 52 53]
  [54 55 56]
  [57 58 59]]]
b1.shape= (1, 2, 3)
b1=
 [[[6 7 8]
  [3 4 5]]]


In [40]:
import numpy as np
ba=3
a1=np.arange(ba*4*4).reshape(ba,4,4)
assert(ba==3,a1.ndim==3)
print('a1.shape=',a1.shape)
print('a1=\n',a1)
b1=np.zeros((ba,2,9,2)) 
print('b1.shape=',b1.shape)
for r in range(2):
    for c in range(2):
        b1[:,r,:,c]=a1[:,r:r+3,c:c+3].reshape(ba,-1)
print('b1=\n',b1)

c1=np.zeros(a1.shape) 
print('c1.shape=',c1.shape)
for r in range(2):
    for c in range(2):
        c1[:,r:r+3,c:c+3]=b1[:,r,:,c].reshape(ba,3,3)
print('c1=\n',c1)

a1.shape= (3, 4, 4)
a1=
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
b1.shape= (3, 2, 9, 2)
b1=
 [[[[ 0.  1.]
   [ 1.  2.]
   [ 2.  3.]
   [ 4.  5.]
   [ 5.  6.]
   [ 6.  7.]
   [ 8.  9.]
   [ 9. 10.]
   [10. 11.]]

  [[ 4.  5.]
   [ 5.  6.]
   [ 6.  7.]
   [ 8.  9.]
   [ 9. 10.]
   [10. 11.]
   [12. 13.]
   [13. 14.]
   [14. 15.]]]


 [[[16. 17.]
   [17. 18.]
   [18. 19.]
   [20. 21.]
   [21. 22.]
   [22. 23.]
   [24. 25.]
   [25. 26.]
   [26. 27.]]

  [[20. 21.]
   [21. 22.]
   [22. 23.]
   [24. 25.]
   [25. 26.]
   [26. 27.]
   [28. 29.]
   [29. 30.]
   [30. 31.]]]


 [[[32. 33.]
   [33. 34.]
   [34. 35.]
   [36. 37.]
   [37. 38.]
   [38. 39.]
   [40. 41.]
   [41. 42.]
   [42. 43.]]

  [[36. 37.]
   [37. 38.]
   [38. 39.]
   [40. 41.]
   [41. 42.]
   [42. 43.]
   [44. 45.]
   [45. 46.]
   [46. 47.]]]]
c1.shape= (3, 4, 4)
c1=
 [[[ 0

<>:4: SyntaxWarning: assertion is always true, perhaps remove parentheses?
<>:4: SyntaxWarning: assertion is always true, perhaps remove parentheses?
<ipython-input-40-47a069afe2c7>:4: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(ba==3,a1.ndim==3)


In [17]:
import numpy as np
ba=3
# l1=np.zeros((ba,1),dtype=int)
# l1[:,0]=np.arange(ba)+2
# l1=l1.reshape(-1)
# l1=np.random.randint(10,size=(ba,1))
l1=np.random.randint(10,size=(ba))
print('l1.shape=',l1.shape)
print('l1=\n',l1)
lv1=np.zeros((ba,10,1))
print('lv1.shape=',lv1.shape)
nba=np.arange(ba)
print('nba.shape=',nba.shape)
print('nba=\n',nba)
# x2=lv1[np.arange(ba),l1,0]
# x2[:]=1
# lv1[np.arange(ba),l1,0][:]=1
# lv1[np.arange(ba),0,0][:]=1
# lv1[:,l1,0][:]=1
# lv1[np.arange(ba),l1,0]=1
lv1[np.arange(ba),l1,:]=1
# lv1[0,1,:][:]=1
# x2=lv1[np.arange(ba),l1,:]
print('np.arange(ba).shape=',np.arange(ba).shape)
# print('x2.shape=',x2.shape)
# print('x2=\n',x2)
print('lv1.shape=',lv1.shape)
# print('lv1=\n',lv1.T)
print('lv1=\n',lv1.transpose(0,2,1))

l1.shape= (3,)
l1=
 [8 0 5]
lv1.shape= (3, 10, 1)
nba.shape= (3,)
nba=
 [0 1 2]
np.arange(ba).shape= (3,)
lv1.shape= (3, 10, 1)
lv1=
 [[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]

 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]]


In [171]:
import numpy as np
a1=np.random.randint(10,size=(1,5))
b1=1.0
c1=np.array(0.0)
print('c1.shape=',c1.shape)
print('c1.dtype=',c1.dtype)
print('c1=\n',c1)

c1.shape= ()
c1.dtype= float64
c1=
 0.0
