In [7]:
import numpy as np
import mnist
import copy
from matplotlib import pyplot as plt 
import pickle
import sys
import time


In [1]:
import tensorflow as tf
tf.__version__

'2.4.1'

In [7]:
import numpy as np
a1=np.arange(3*3).reshape(3,3)
# b1=np.outer(a1,a1)
# b1=np.kron(a1,a1)
b1=np.einsum('ij,kl->ijkl',a1,a1)
print('a1=\n',a1)
print('b1.shape=',b1.shape)
print('b1=\n',b1)


a1=
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
b1.shape= (3, 3, 3, 3)
b1=
 [[[[ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]]

  [[ 0  1  2]
   [ 3  4  5]
   [ 6  7  8]]

  [[ 0  2  4]
   [ 6  8 10]
   [12 14 16]]]


 [[[ 0  3  6]
   [ 9 12 15]
   [18 21 24]]

  [[ 0  4  8]
   [12 16 20]
   [24 28 32]]

  [[ 0  5 10]
   [15 20 25]
   [30 35 40]]]


 [[[ 0  6 12]
   [18 24 30]
   [36 42 48]]

  [[ 0  7 14]
   [21 28 35]
   [42 49 56]]

  [[ 0  8 16]
   [24 32 40]
   [48 56 64]]]]


In [16]:
import  pandas as pd
pd.set_option('max_columns',None)
pd.set_option('max_row',None)


In [7]:
import numpy as np
a1=np.arange(2e4).reshape(-1,1)
# print('a1=\n',a1)
b1=a1@a1.T
# print('b1=\n',b1)
print('b1.shape=',b1.shape)



b1.shape= (20000, 20000)
