In [4]:
import numpy as np
a=np.ones((2,5,6))
print('a.shape=',a.shape)
# print('a=\n',a)
b=np.arange(2*3*4).reshape(3,2,4)
print('b.shape=',b.shape)
# print('b=\n',b)
c=np.einsum('ijk->jik',b)
print('c.shape=',c.shape)
# print('c=\n',c)
d=np.einsum('mij,kml->mijkl',a,b)
print('d.shape=',d.shape)
# print('d=\n',d)
e=np.einsum('mij,mkl->mijkl',a,c)
print('e.shape=',e.shape)
# print('e=\n',e)
f=d-e
print('f.shape=',f.shape)
print('f=\n',f)

a.shape= (2, 5, 6)
b.shape= (3, 2, 4)
c.shape= (2, 3, 4)
d.shape= (2, 5, 6, 3, 4)
e.shape= (2, 5, 6, 3, 4)
f.shape= (2, 5, 6, 3, 4)
f=
 [[[[[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]]


  [[[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]]


  [[[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
  

In [7]:
import numpy as np
a=np.ones((2,3,5,6))
print('a.shape=',a.shape)
# print('a=\n',a)
b=np.arange(2*3*7).reshape(7,3,2)
print('b.shape=',b.shape)
# print('b=\n',b)
c=np.einsum('ijk->kji',b)
print('c.shape=',c.shape)
# print('c=\n',c)
d=np.einsum('mnij,knm->mnijk',a,b)
print('d.shape=',d.shape)
# print('d=\n',d)s
e=np.einsum('mnij,mnk->mnijk',a,c)
print('e.shape=',e.shape)
# print('e=\n',e)
f=d-e
print('f.shape=',f.shape)
# print('f=\n',f)
g=d==e
# print('g.shape=',g.shape)
print('g=\n',g)

a.shape= (2, 3, 5, 6)
b.shape= (7, 3, 2)
c.shape= (2, 3, 7)
d.shape= (2, 3, 5, 6, 7)
e.shape= (2, 3, 5, 6, 7)
f.shape= (2, 3, 5, 6, 7)
g=
 [[[[[ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]]

   [[ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]]

   [[ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]]

   [[ True  True  True ... 

In [21]:
import numpy as np
# a=np.arange(2*5*4).reshape(2,5,4)
a=np.ones((100000,1))
# a=np.ones((100000,1),dtype=np.float32)
c=np.ones((20,80,80))
b=a@a.T
# d=np.einsum('mij,mkl->mijkl',c,c)
print('a.shape=',a.shape)
print('b.shape=',b.shape)
print('c.shape=',c.shape)
print('d.shape=',d.shape)
# print('a=\n',a)
c.shape[1:3]

MemoryError: Unable to allocate 74.5 GiB for an array with shape (100000, 100000) and data type float64

In [23]:
import numpy as np
a=np.arange(2*3*3).reshape(2,3,3)
# b=a.transpose(0,2,1)
b=a.T(0,2,1)
# print('a.shape=',a.shape)
# print('a=\n',a)
# b=np.einsum('bii->bi',a)
print('b.shape=',b.shape)
print('b=\n',b)
# np.einsum('bii->bi',a)[:]=66
# print('a.shape=',a.shape)
# print('a=\n',a)

TypeError: 'numpy.ndarray' object is not callable

In [18]:
# a=np.zeros((XXr.shape))
a=np.zeros((2,3,3))
np.einsum('mii->mi',a)[:]=3*3
print('a.shape=',a.shape)
print('a=\n',a)



a.shape= (2, 3, 3)
a=
 [[[9. 0. 0.]
  [0. 9. 0.]
  [0. 0. 9.]]

 [[9. 0. 0.]
  [0. 9. 0.]
  [0. 0. 9.]]]
