In [2]:
import cnn
import numpy as np
import imp
imp.reload(cnn)
# (params,params_init,g,g_d)=cnn.init_params(lays=2)
# params=cnn.hyperparams_test(params,params_init,g,g_d,nloop=4,lr0=2e-3,klr=0.9995,batch=64,isupdate=1,isl2grad=1)
# cnn.show(params,g)

params: ch= [1, 2, 3, 4, 10]
params: lays= 4
params: k0.shape= (2, 1, 3, 3)
params: gama0.shape= (2, 1, 1)
params: beta0.shape= (2, 1, 1)
params: k1.shape= (3, 2, 3, 3)
params: gama1.shape= (3, 1, 1)
params: beta1.shape= (3, 1, 1)
params: k2.shape= (4, 3, 3, 3)
params: gama2.shape= (4, 1, 1)
params: beta2.shape= (4, 1, 1)
params: w3.shape= (10, 4, 28, 28)
x.shape= (3, 1, 28, 28)
slope: running k0.shape= (2, 1, 3, 3)
slope: k0[1/18] slope = -3.5725138097575377
slope: k0[2/18] slope = -4.792706130274382
slope: k0[3/18] slope = -0.7858602145915937
slope: k0[4/18] slope = 2.6700514389688124
slope: k0[6/18] slope = 0.5259345009278604
slope: k0[9/18] slope = -0.8153670847832472
slope: k0[12/18] slope = 6.212949190143035
slope: running gama0.shape= (2, 1, 1)
slope: gama0[1/2] slope = 2.772959384600426
slope: gama0[2/2] slope = -2.7729594094694217
slope: running beta0.shape= (2, 1, 1)
slope: beta0[1/2] slope = -7.09746165910019
slope: beta0[2/2] slope = 17.13404312226885
slope: running k1.shap

slope: w3 running loop=15700/31360
slope: w3 running loop=15800/31360
slope: w3 running loop=15900/31360
slope: w3 running loop=16000/31360
slope: w3 running loop=16100/31360
slope: w3 running loop=16200/31360
slope: w3 running loop=16300/31360
slope: w3 running loop=16400/31360
slope: w3 running loop=16500/31360
slope: w3 running loop=16600/31360
slope: w3 running loop=16700/31360
slope: w3 running loop=16800/31360
slope: w3 running loop=16900/31360
slope: w3 running loop=17000/31360
slope: w3 running loop=17100/31360
slope: w3 running loop=17200/31360
slope: w3 running loop=17300/31360
slope: w3 running loop=17400/31360
slope: w3 running loop=17500/31360
slope: w3 running loop=17600/31360
slope: w3 running loop=17700/31360
slope: w3 running loop=17800/31360
slope: w3 running loop=17900/31360
slope: w3 running loop=18000/31360
slope: w3 running loop=18100/31360
slope: w3 running loop=18200/31360
slope: w3 running loop=18300/31360
slope: w3 running loop=18400/31360
slope: w3 running lo

<module 'cnn' from '/home/qc/proj_py/cnn.py'>

In [8]:
bp: ki=
 [[[[ 1.13940068 -1.23482582  0.40234164]
   [-0.68481009 -0.87079715 -0.57884966]
   [-0.31155253  0.05616534 -1.16514984]]

  [[ 0.90082649  0.46566244 -1.53624369]
   [ 1.48825219  1.89588918  1.17877957]
   [-0.17992484 -1.07075262  1.05445173]]

  [[-0.40317695  1.22244507  0.20827498]
   [ 0.97663904  0.3563664   0.70657317]
   [ 0.01050002  1.78587049  0.12691209]]]

params: ch= [1, 2, 3, 4, 10]
params: k0.shape= (2, 1, 3, 3)
params: gama0.shape= (2, 1, 1)
params: beta0.shape= (2, 1, 1)
params: k1.shape= (3, 2, 3, 3)
params: gama1.shape= (3, 1, 1)
params: beta1.shape= (3, 1, 1)
params: k2.shape= (4, 3, 3, 3)
params: gama2.shape= (4, 1, 1)
params: beta2.shape= (4, 1, 1)
params: w3.shape= (10, 4, 5, 6)
params: gama3.shape= (10, 1, 1)
params: beta3.shape= (10, 1, 1)
x.shape= (2, 1, 5, 6)
cross_entropy
fp: Y.shape= (2, 10, 1, 1)
Y.shape= (2, 10, 1, 1)
Y=
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
YL=
 [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


<module 'cnn' from '/home/qc/proj_py/cnn.py'>

In [27]:
# def maxpooling(im,k=2):
#     (ba,c,h,w)=im.shape
#     (hp,wp)=(int(h/k),int(w/k))
#     #	(ba,cp,hp,wp)=imp.shape
#     strd=(c*h*w,h*w,w*k,k,w,1)
#     strd=(i*im.itemsize for i in strd)
#     col=np.lib.stride_tricks.as_strided(im,shape=(ba,c,hp,wp,k,k),strides=strd)
#     ##	cols=np.zeros((x.shape[0],h,w,k*k))
#     #	cols=np.zeros(ba,c,h,w,k,k))
#     #	for r in range(h):
#     #		for c in range(w):
#     #			cols[:,r,:,c]=X[:,k*r:k*r+k,k*c:k*c+k].reshape(X.shape[0],-1)
#     maxcol=np.max(col,(-2,-1))
# #     maxcol=col
#     return maxcol

def maxpooling(im,k=2):
	(ba,c,h,w)=im.shape
	(hp,wp)=(int(h/k),int(w/k))
	strd=(c*h*w,h*w,w*k,k,w,1)
	strd=(i*im.itemsize for i in strd)
	col=np.lib.stride_tricks.as_strided(im,shape=(ba,c,hp,wp,k,k),strides=strd)
	maxcol=np.max(col,(-2,-1))
	return maxcol


import numpy as np
(ba,c,h,w,k)=(2,2,4,4,2)
a1=np.arange(ba*c*h*w).reshape(ba,c,h,w)+1
print('a1.shape=',a1.shape)
print('a1=\n',a1)
b1=maxpooling(a1)
print('b1.shape=',b1.shape)
print('b1=\n',b1)

a1.shape= (2, 2, 4, 4)
a1=
 [[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]
   [25 26 27 28]
   [29 30 31 32]]]


 [[[33 34 35 36]
   [37 38 39 40]
   [41 42 43 44]
   [45 46 47 48]]

  [[49 50 51 52]
   [53 54 55 56]
   [57 58 59 60]
   [61 62 63 64]]]]
b1.shape= (2, 2, 2, 2)
b1=
 [[[[ 6  8]
   [14 16]]

  [[22 24]
   [30 32]]]


 [[[38 40]
   [46 48]]

  [[54 56]
   [62 64]]]]
