In [19]:
import numpy as np
a1=np.arange(3*2*2).reshape(3,2,2)+1
b1=(a1-a1.max((-2,-1),keepdims=1)+1)
c1=b1.copy()
c1[b1<1]=0

print('a1=\n',a1)
print('b1=\n',b1)
print('c1=\n',c1)
print('a1.shape=',a1.shape)
print('b1.shape=',b1.shape)

a1=
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
b1=
 [[[-2 -1]
  [ 0  1]]

 [[-2 -1]
  [ 0  1]]

 [[-2 -1]
  [ 0  1]]]
c1=
 [[[0 0]
  [0 1]]

 [[0 0]
  [0 1]]

 [[0 0]
  [0 1]]]
a1.shape= (3, 2, 2)
b1.shape= (3, 2, 2)


In [62]:
import numpy as np
def im2col(im,k=3,s=1,pad=1):
#	assert(im.ndim==4 and im.shape[-1]==1)
#	im2=np.pad(im,((0,0),(0,0),(0,int(np.ceil(im.shape[-2]%2))),(0,int(np.ceil(im.shape[-1]%2)))))
    p=int(k/2)
    (ba,c,h,w)=im.shape
    if pad==1: imp=np.pad(im,((0,0),(0,0),(p,p),(p,p)))
    else: imp=im
    (ba,cp,hp,wp)=imp.shape
    strd=(c*hp*wp,hp*wp,wp*s,s,wp,1)
    strd=(i*imp.itemsize for i in strd)
    # 	col=np.lib.stride_tricks.as_strided(imp,shape=(ba,c,h,w,k,k),strides=strd)
    col=np.lib.stride_tricks.as_strided(imp,shape=(ba,c,int((hp-k)/s)+1,int((wp-k)/s)+1,k,k),strides=strd)
    return col

h,w=(6,6)
a1=np.arange(1*1*h*w).reshape(1,1,h,w)+1
# b1=im2col(a1,s=1,pad=1)
# b1=im2col(a1,s=1,pad=0)
# b1=im2col(a1,s=3,pad=0)
b1=im2col(a1,k=2,s=2,pad=0)
print('a1.shape=',a1.shape)o
print('b1.shape=',b1.shape)
print('a1=\n',a1.squeeze())
print('b1=\n',b1.squeeze())



a1.shape= (1, 1, 6, 6)
b1.shape= (1, 1, 3, 3, 2, 2)
a1=
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
b1=
 [[[[ 1  2]
   [ 7  8]]

  [[ 3  4]
   [ 9 10]]

  [[ 5  6]
   [11 12]]]


 [[[13 14]
   [19 20]]

  [[15 16]
   [21 22]]

  [[17 18]
   [23 24]]]


 [[[25 26]
   [31 32]]

  [[27 28]
   [33 34]]

  [[29 30]
   [35 36]]]]


In [43]:
import numpy as np
np.log2(7)



2.807354922057604

In [ ]:
a2=
 [[[[ 0  0  0  0  0  0]
   [ 0  1  2  3  4  0]
   [ 0  5  6  7  8  0]
   [ 0  9 10 11 12  0]
   [ 0 13 14 15 16  0]
   [ 0  0  0  0  0  0]]

  [[ 0  0  0  0  0  0]
   [ 0 17 18 19 20  0]
   [ 0 21 22 23 24  0]
   [ 0 25 26 27 28  0]
   [ 0 29 30 31 32  0]
   [ 0  0  0  0  0  0]]]]