In [2]:
import numpy as np
import mnist

In [5]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
b=np.ones((2,2)).reshape(-1)
b

array([1., 1., 1., 1.])

In [60]:
# c=np.zeros([2,2,4,4])
# c=np.arange(64).reshape(2,2,4,4)
c=np.arange(2*2*4*4,dtype=int).reshape(2,2,4,4)
c

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]]],


       [[[32, 33, 34, 35],
         [36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]],

        [[48, 49, 50, 51],
         [52, 53, 54, 55],
         [56, 57, 58, 59],
         [60, 61, 62, 63]]]])

In [1]:
c[:,0,:,:]

NameError: name 'c' is not defined

In [82]:
d=np.ones((4,2),dtype=int)
d

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [8]:
a=mnist.train_img[0].reshape(28,28)
a
# a.shape

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [44]:
a=np.arange(1*3*3).reshape(3,3)
a.shape
aa=a
aa

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
b=np.ones((2,2))
b.shape
b

array([[1., 1.],
       [1., 1.]])

In [27]:
a[0:2,0:2].reshape(-1)


array([0, 1, 3, 4])

In [28]:
a[1:3,0:2].reshape(-1)


array([3, 4, 6, 7])

In [29]:
a[0:2,1:3].reshape(-1)


array([1, 2, 4, 5])

In [30]:
a[1:3,1:3].reshape(-1)

array([4, 5, 7, 8])

In [36]:
k=np.ones((2,2),dtype=int).reshape(-1)
k

array([1, 1, 1, 1])

In [37]:
c=np.ones((2,2,4),dtype=int)
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [38]:
c@k

array([[4, 4],
       [4, 4]])

In [42]:
c[0,0,:]=a[0:2,0:2].reshape(-1)
c[0,1,:]=a[1:3,0:2].reshape(-1)
c[1,0,:]=a[0:2,1:3].reshape(-1)
c[1,1,:]=a[1:3,1:3].reshape(-1)
c

array([[[0, 1, 3, 4],
        [3, 4, 6, 7]],

       [[1, 2, 4, 5],
        [4, 5, 7, 8]]])

In [43]:
c@k

array([[ 8, 20],
       [12, 24]])

In [46]:
aa

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
c=np.ones((2,2,4),dtype=int)
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [66]:
c=np.ones((2,2,4),dtype=int)
cc=np.ones_like(c)
# cc[1,1,:]=a[1:3,1:3].reshape(-1)
for i in range(2):
    for j in range(2):
        cc[i,j,:]=a[j:j+2,i:i+2].reshape(-1)
cc

array([[[0, 1, 3, 4],
        [3, 4, 6, 7]],

       [[1, 2, 4, 5],
        [4, 5, 7, 8]]])

In [72]:
a=np.arange(1*3*3).reshape(3,3)
a=np.pad(a,1)
a

array([[0, 0, 0, 0, 0],
       [0, 0, 1, 2, 0],
       [0, 3, 4, 5, 0],
       [0, 6, 7, 8, 0],
       [0, 0, 0, 0, 0]])

In [149]:
k=3
m=3
n=4
kk=np.zeros((k,k),dtype=int)
kk[1,1]=1
kk=kk.reshape(-1)
aa=np.arange(m*n,dtype=int).reshape(m,n)
aaa=np.pad(aa,1)
aaa
# kk

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  2,  3,  0],
       [ 0,  4,  5,  6,  7,  0],
       [ 0,  8,  9, 10, 11,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [144]:
bb=np.zeros((4,3,9),dtype=int)
for j in range(n):
    for i in range(m):
        bb[j,i,:]=aaa[i:i+k,j:j+k].reshape(-1)
        
# for j in range(2):
#     for i in range(1):
#         bb[j,i,:]=aaa[i:i+k,j:j+k].reshape(-1)
# aa
# bb[0,0,:].shape
# aa[0:0+k,0:0+k].reshape(-1).shape
# aaa[0:0+k,0:0+k].reshape(-1)
# bb[0,0,:]=aaa[0:0+k,0:0+k].reshape(-1)
# bb[0,0,:]
bb
# kk

array([[[ 0,  0,  0,  0,  0,  1,  0,  4,  5],
        [ 0,  0,  1,  0,  4,  5,  0,  8,  9],
        [ 0,  4,  5,  0,  8,  9,  0,  0,  0]],

       [[ 0,  0,  0,  0,  1,  2,  4,  5,  6],
        [ 0,  1,  2,  4,  5,  6,  8,  9, 10],
        [ 4,  5,  6,  8,  9, 10,  0,  0,  0]],

       [[ 0,  0,  0,  1,  2,  3,  5,  6,  7],
        [ 1,  2,  3,  5,  6,  7,  9, 10, 11],
        [ 5,  6,  7,  9, 10, 11,  0,  0,  0]],

       [[ 0,  0,  0,  2,  3,  0,  6,  7,  0],
        [ 2,  3,  0,  6,  7,  0, 10, 11,  0],
        [ 6,  7,  0, 10, 11,  0,  0,  0,  0]]])

In [172]:
bb


array([[[ 0,  0,  0,  0,  0,  1,  0,  4,  5],
        [ 0,  0,  1,  0,  4,  5,  0,  8,  9],
        [ 0,  4,  5,  0,  8,  9,  0,  0,  0]],

       [[ 0,  0,  0,  0,  1,  2,  4,  5,  6],
        [ 0,  1,  2,  4,  5,  6,  8,  9, 10],
        [ 4,  5,  6,  8,  9, 10,  0,  0,  0]],

       [[ 0,  0,  0,  1,  2,  3,  5,  6,  7],
        [ 1,  2,  3,  5,  6,  7,  9, 10, 11],
        [ 5,  6,  7,  9, 10, 11,  0,  0,  0]],

       [[ 0,  0,  0,  2,  3,  0,  6,  7,  0],
        [ 2,  3,  0,  6,  7,  0, 10, 11,  0],
        [ 6,  7,  0, 10, 11,  0,  0,  0,  0]]])

In [173]:
bb[0,:,:]

array([[0, 0, 0, 0, 0, 1, 0, 4, 5],
       [0, 0, 1, 0, 4, 5, 0, 8, 9],
       [0, 4, 5, 0, 8, 9, 0, 0, 0]])

In [163]:
kk

array([0, 0, 0, 0, 1, 0, 0, 0, 0])

In [170]:
bb@kk
# bb.dot(kk)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [160]:
dd

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [161]:
aa

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])