In [4]:
import numpy as np
a=np.ones((2,5,6))
print('a.shape=',a.shape)
# print('a=\n',a)
b=np.arange(2*3*4).reshape(3,2,4)
print('b.shape=',b.shape)
# print('b=\n',b)
c=np.einsum('ijk->jik',b)
print('c.shape=',c.shape)
# print('c=\n',c)
d=np.einsum('mij,kml->mijkl',a,b)
print('d.shape=',d.shape)
# print('d=\n',d)
e=np.einsum('mij,mkl->mijkl',a,c)
print('e.shape=',e.shape)
# print('e=\n',e)
f=d-e
print('f.shape=',f.shape)
print('f=\n',f)

a.shape= (2, 5, 6)
b.shape= (3, 2, 4)
c.shape= (2, 3, 4)
d.shape= (2, 5, 6, 3, 4)
e.shape= (2, 5, 6, 3, 4)
f.shape= (2, 5, 6, 3, 4)
f=
 [[[[[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]]


  [[[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]]


  [[[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
  

In [223]:
import numpy as np
# a=np.ones((2,3,5,6))
# a=a.reshape((1,)+a.shape)
# print('a.shape=',a.shape)
# print('a=\n',a)
(ba,m,n)=(2,4,4)
kf=3
p=int(kf/2)
b=np.arange(ba*m*n).reshape(ba,m,1,n)
print('b.shape=',b.shape)
# b=np.pad(b,((0,0),(p,p),(0,0),(p,p)))
print('b.shape=',b.shape)
print('b=\n',b)
(ba,rr,Non,cc)=b.shape
cols_r=rr-kf+1
cols_c=cc-kf+1
cols=np.zeros((ba,cols_r,kf*kf,cols_c))
# # cols=np.zeros(b.shape[:-2]+(9,)+b.shape[-1:])
# print('cols.shape=',cols.shape)

# # cols=np.zeros((2,2,9,2))
# print('cols.shape=',cols.shape)
for r in range(cols_r):
    for c in range(cols_c):
#         print(b[:,r:r+3,:,c:c+3].shape)
#         print(b[:,r:r+3,:,c:c+3].reshape(b.shape[0],-1).shape)
#         print('r=',r)
#         print('c=',c)
#         cols[:,r,:,c]=b[:,r:r+3,:,c:c+3].reshape(b.shape[0],-1)
        cols[:,r,:,c]=b[:,r:r+3,0,c:c+3].reshape(b.shape[0],-1)
        

print('cols=\n',cols)
# c=b.reshape(b.shape[0:2]+(,1,)+b.shape[-1])
# c=b.reshape(b.shape[0:-1]+b.shape[-1])
# c=b.reshape(b.shape[0:-1]+tuple([-1]))
# c=b.reshape(b.shape[0:-1]+b.shape[-1])
# c=np.expand_dims(b,axis=-2)
# # c=np.expand_dims(c,axis=-2)
# print('c.shape=',c.shape)
# print('c=\n',c)
# b.shape[0:-1]


b.shape= (2, 4, 1, 4)
b.shape= (2, 4, 1, 4)
b=
 [[[[ 0  1  2  3]]

  [[ 4  5  6  7]]

  [[ 8  9 10 11]]

  [[12 13 14 15]]]


 [[[16 17 18 19]]

  [[20 21 22 23]]

  [[24 25 26 27]]

  [[28 29 30 31]]]]
cols=
 [[[[ 0.  1.]
   [ 1.  2.]
   [ 2.  3.]
   [ 4.  5.]
   [ 5.  6.]
   [ 6.  7.]
   [ 8.  9.]
   [ 9. 10.]
   [10. 11.]]

  [[ 4.  5.]
   [ 5.  6.]
   [ 6.  7.]
   [ 8.  9.]
   [ 9. 10.]
   [10. 11.]
   [12. 13.]
   [13. 14.]
   [14. 15.]]]


 [[[16. 17.]
   [17. 18.]
   [18. 19.]
   [20. 21.]
   [21. 22.]
   [22. 23.]
   [24. 25.]
   [25. 26.]
   [26. 27.]]

  [[20. 21.]
   [21. 22.]
   [22. 23.]
   [24. 25.]
   [25. 26.]
   [26. 27.]
   [28. 29.]
   [29. 30.]
   [30. 31.]]]]


In [232]:
import numpy as np
a=np.arange(2*4*1*4).reshape(2,4,1,4)
b=np.mean(a,axis=(1,2,3),keepdims=1)
print('b.shape=',b.shape)
print('b=\n',b)
print('a.shape=',a.shape)
a=a.reshape((1,)+a.shape+(1,))
print('a.shape=',a.shape)

b.shape= (2, 1, 1, 1)
b=
 [[[[ 7.5]]]


 [[[23.5]]]]
a.shape= (2, 4, 1, 4)
a.shape= (1, 2, 4, 1, 4, 1)
