In [5]:
import numpy as np
a=np.arange(9).reshape(1,9)+1
print(a)
b=np.ones((1,9))*2
print(b)
print(b/a)

[[1 2 3 4 5 6 7 8 9]]
[[2. 2. 2. 2. 2. 2. 2. 2. 2.]]
[[2.         1.         0.66666667 0.5        0.4        0.33333333
  0.28571429 0.25       0.22222222]]


In [6]:
np.log(1e-23)

-52.95945713886305

In [30]:
a=np.arange(9).reshape(1,9)+1
a*2

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18]])

In [31]:
a=np.maximum(a,3)
a

array([[3, 3, 3, 4, 5, 6, 7, 8, 9]])

In [36]:
aa= np.array([[3, 0, 3, 0, 5, 6, 7, 8, 9]])

In [38]:
aa[aa==0]=3232
aa

array([[   3, 3232,    3, 3232,    5,    6,    7,    8,    9]])

In [21]:
def softmax(x,a=1e-23): 
    exp=np.exp(x-x.max())
    return exp/exp.sum()+a
softmax(a)

array([[2.12078996e-04, 5.76490482e-04, 1.56706360e-03, 4.25972051e-03,
        1.15791209e-02, 3.14753138e-02, 8.55587737e-02, 2.32572860e-01,
        6.32198578e-01]])