In [358]:
import numpy as np
mm=3;rr=3;cc=3
a1=np.arange(mm*rr*cc).reshape(mm,rr,cc)
b1=np.ones((3,3,3))
# o1=np.ones((3,1))
# b2=np.array([o1,o1*3,o1*21])
print('a1.shape=',a1.shape)
print('b1.shape=',b1.shape)
print('a1=')
print(a1)
print('b1=')
print(b1)

a1.shape= (3, 3, 3)
b1.shape= (3, 3, 3)
a1=
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
b1=
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
import tensorflow as tf
tf.__version__

In [406]:
print( type( tuple([1]) ) )

<class 'tuple'>


In [9]:
import numpy as np
aa=np.arange(2*3*1).reshape(2,3,1)
print('aa=',aa)
# bb=np.mean(aa,axis=1)
bb=np.mean(aa,axis=1,keepdims=1)
print(bb.shape)
print('bb=',bb)
cc=aa-bb
print('cc=',cc)

aa= [[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]
(2, 1, 1)
bb= [[[1.]]

 [[4.]]]
cc= [[[-1.]
  [ 0.]
  [ 1.]]

 [[-1.]
  [ 0.]
  [ 1.]]]


In [41]:
import numpy as np
aa=np.arange(2*3*3).reshape(2,3,3)
print('aa.shape=',aa.shape)
print('aa=\n',aa)
t1=np.eye(3)
print('t1.shape=',t1.shape)
print('t1=\n',t1)
t2=np.ones((3,3))
print('t2.shape=',t2.shape)
print('t2=\n',t2)
# bb=aa-t1
bb=aa-t2
print('bb.shape=',bb.shape)
print('bb=\n',bb)
    
# bb.shape[0]

# tt=aa.mean(axis=0)
tt=aa.mean(axis=1)
print('tt.shape=',tt.shape)
print('tt=\n',tt)


aa.shape= (2, 3, 3)
aa=
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
t1.shape= (3, 3)
t1=
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
t2.shape= (3, 3)
t2=
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
bb.shape= (2, 3, 3)
bb=
 [[[-1.  0.  1.]
  [ 2.  3.  4.]
  [ 5.  6.  7.]]

 [[ 8.  9. 10.]
  [11. 12. 13.]
  [14. 15. 16.]]]
tt.shape= (2, 3)
tt=
 [[ 3.  4.  5.]
 [12. 13. 14.]]


In [42]:
import numpy as np
aa=np.arange(2*4*1).reshape(2,4,1)
print('aa.shape=',aa.shape)
print('aa=\n',aa)

tt=aa.mean(axis=0)
# tt=aa.mean(axis=1)
print('tt.shape=',tt.shape)
print('tt=\n',tt)


aa.shape= (2, 4, 1)
aa=
 [[[0]
  [1]
  [2]
  [3]]

 [[4]
  [5]
  [6]
  [7]]]
tt.shape= (4, 1)
tt=
 [[2.]
 [3.]
 [4.]
 [5.]]
