In [206]:
import numpy as np
import copy
def relu(x,kn=1e-3):
    y=copy.deepcopy(x) 
    y=y.reshape(-1)
    y[y<0]=y[y<0]*0.1
    y[y>0]=y[y>0]
    y=y.reshape(x.shape)
    return y
def relu_d(x,kn=1e-3):
    y=x.reshape(-1)
    yt=y
#     print('yt=',yt)
#     print('y=',y)
    y[yt<0]=0.1
    y[yt>=0]=1
    print('yt=',yt)
    print('y=',y)
    y=y.reshape(x.shape)
    return y

In [208]:
a1=np.arange(3*2*2,dtype=np.float32).reshape(3,2,2)
# a1=np.arange(3*2*2).reshape(3,2,2)
a1=a1-6
print(a1.shape)
print(a1)

(3, 2, 2)
[[[-6. -5.]
  [-4. -3.]]

 [[-2. -1.]
  [ 0.  1.]]

 [[ 2.  3.]
  [ 4.  5.]]]


In [195]:
relu(a1)

array([[[-0.6, -0.5],
        [-0.4, -0.3]],

       [[-0.2, -0.1],
        [ 0. ,  1. ]],

       [[ 2. ,  3. ],
        [ 4. ,  5. ]]], dtype=float32)

In [209]:
relu_d(a1)600.00

yt= [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
y= [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)