In [29]:
import numpy as np

In [35]:
# a1=np.arange(10).reshape(1,-1)
a1=np.arange(10)
print(a1.shape)
# a1.argmax()
print(a1)


(10,)
[0 1 2 3 4 5 6 7 8 9]


In [38]:
b1=np.diag(a1)
print(b1.shape)
print(b1)

(10, 10)
[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 9]]
