In [358]:
import numpy as np
mm=3;rr=3;cc=3
a1=np.arange(mm*rr*cc).reshape(mm,rr,cc)
b1=np.ones((3,3,3))
# o1=np.ones((3,1))
# b2=np.array([o1,o1*3,o1*21])
print('a1.shape=',a1.shape)
print('b1.shape=',b1.shape)
print('a1=')
print(a1)
print('b1=')
print(b1)

a1.shape= (3, 3, 3)
b1.shape= (3, 3, 3)
a1=
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
b1=
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [2]:
import tensorflow as tf
tf.__version__

'2.4.1'

In [1]:
print( type( tuple([1]) ) )

<class 'tuple'>


In [4]:
import numpy as np
a1={}
a1['aa']=11
a1['bb']=22

a1



{'aa': 11, 'bb': 22}

In [81]:
import numpy as np
aa={}
aa['b0']=11
aa['b1']=22
aa['b2']=33
# aa['beta1']=55
# aa['beta2']=66
# aa['c2']=77
# aa['c3']=88
cc={}
for k,v in aa.items():
#     if   :
#     if k[0]=='b' and k[1]=='2':
#     if k[0]=='b' and isdigit(k[1]) :
#     if not (k[0]=='b' and   k[1].isdigit ()):
#         print('v=',v)
    print('k=',k)
    cc['l2_'+k]=[]
    cc['l2_'+k].append(v)
for k,v in aa.items():
#     if   :
#     if k[0]=='b' and k[1]=='2':
#     if k[0]=='b' and isdigit(k[1]) :
#     if not (k[0]=='b' and   k[1].isdigit ()):
#         print('v=',v)
    print('k=',k)
#     cc['l2_'+k]=[]
    cc['l2_'+k].append(v)

#     v.append(k)
#            (k+str(d))=[]
#         print(k[0])
aa
cc
print(len(aa))

k= b0
k= b1
k= b2
k= b0
k= b1
k= b2
3


In [93]:
np.exp(d1)

array([[[1.00000000e+00, 1.00000000e+00],
        [2.71828183e+00, 7.38905610e+00],
        [7.38905610e+00, 5.45981500e+01]],

       [[2.00855369e+01, 4.03428793e+02],
        [5.45981500e+01, 2.98095799e+03],
        [1.48413159e+02, 2.20264658e+04]]])

In [30]:
d1=np.einsum('ijk,mln->ijkmln',a1,b2)
print(d1.shape)
print(d1)

(2, 3, 4, 2, 4, 2)
[[[[[[ 0.  0.]
     [ 0.  0.]
     [ 0.  0.]
     [ 0.  0.]]

    [[ 0.  0.]
     [ 0.  0.]
     [ 0.  0.]
     [ 0.  0.]]]


   [[[ 1.  1.]
     [ 1.  1.]
     [ 1.  1.]
     [ 1.  1.]]

    [[ 2.  2.]
     [ 2.  2.]
     [ 2.  2.]
     [ 2.  2.]]]


   [[[ 2.  2.]
     [ 2.  2.]
     [ 2.  2.]
     [ 2.  2.]]

    [[ 4.  4.]
     [ 4.  4.]
     [ 4.  4.]
     [ 4.  4.]]]


   [[[ 3.  3.]
     [ 3.  3.]
     [ 3.  3.]
     [ 3.  3.]]

    [[ 6.  6.]
     [ 6.  6.]
     [ 6.  6.]
     [ 6.  6.]]]]



  [[[[ 4.  4.]
     [ 4.  4.]
     [ 4.  4.]
     [ 4.  4.]]

    [[ 8.  8.]
     [ 8.  8.]
     [ 8.  8.]
     [ 8.  8.]]]


   [[[ 5.  5.]
     [ 5.  5.]
     [ 5.  5.]
     [ 5.  5.]]

    [[10. 10.]
     [10. 10.]
     [10. 10.]
     [10. 10.]]]


   [[[ 6.  6.]
     [ 6.  6.]
     [ 6.  6.]
     [ 6.  6.]]

    [[12. 12.]
     [12. 12.]
     [12. 12.]
     [12. 12.]]]


   [[[ 7.  7.]
     [ 7.  7.]
     [ 7.  7.]
     [ 7.  7.]]

    [[14. 14.]
     [14. 14.]
     

In [29]:
c1=np.einsum('ijk,mli->ijkml',a1,b2)
print(c1.shape)
print(c1)

(2, 3, 4, 2, 4)
[[[[[ 0.  0.  0.  0.]
    [ 0.  0.  0.  0.]]

   [[ 1.  1.  1.  1.]
    [ 2.  2.  2.  2.]]

   [[ 2.  2.  2.  2.]
    [ 4.  4.  4.  4.]]

   [[ 3.  3.  3.  3.]
    [ 6.  6.  6.  6.]]]


  [[[ 4.  4.  4.  4.]
    [ 8.  8.  8.  8.]]

   [[ 5.  5.  5.  5.]
    [10. 10. 10. 10.]]

   [[ 6.  6.  6.  6.]
    [12. 12. 12. 12.]]

   [[ 7.  7.  7.  7.]
    [14. 14. 14. 14.]]]


  [[[ 8.  8.  8.  8.]
    [16. 16. 16. 16.]]

   [[ 9.  9.  9.  9.]
    [18. 18. 18. 18.]]

   [[10. 10. 10. 10.]
    [20. 20. 20. 20.]]

   [[11. 11. 11. 11.]
    [22. 22. 22. 22.]]]]



 [[[[12. 12. 12. 12.]
    [24. 24. 24. 24.]]

   [[13. 13. 13. 13.]
    [26. 26. 26. 26.]]

   [[14. 14. 14. 14.]
    [28. 28. 28. 28.]]

   [[15. 15. 15. 15.]
    [30. 30. 30. 30.]]]


  [[[16. 16. 16. 16.]
    [32. 32. 32. 32.]]

   [[17. 17. 17. 17.]
    [34. 34. 34. 34.]]

   [[18. 18. 18. 18.]
    [36. 36. 36. 36.]]

   [[19. 19. 19. 19.]
    [38. 38. 38. 38.]]]


  [[[20. 20. 20. 20.]
    [40. 40. 40. 40.]]

   [[2

In [251]:
c=np.max(a1,axis=1,keepdims=1)
c

array([[[2]],

       [[5]],

       [[8]]])

In [255]:
d=a1/c
d

array([[[0.   ],
        [0.5  ],
        [1.   ]],

       [[0.6  ],
        [0.8  ],
        [1.   ]],

       [[0.75 ],
        [0.875],
        [1.   ]]])

In [237]:
# c = a1[axis=1]==b1[axis=1]
# b1=a1
c = a1==b1
print(c.shape)
c

(3, 3, 1)


array([[[False],
        [ True],
        [False]],

       [[ True],
        [False],
        [False]],

       [[False],
        [False],
        [False]]])

In [239]:
d=np.einsum('ijk->ik',c)
d

array([[0.33333333],
       [0.33333333],
       [0.        ]])

In [244]:
d=np.sum(c,axis=1)/c.shape[1]


array([[0.33333333],
       [0.33333333],
       [0.        ]])

In [171]:
a1[[0,1],[t2],:]

array([[[ 0,  1,  2],
        [12, 13, 14]]])

In [169]:
t1=np.arange(2*1*1).reshape(2,1,1)
print(t1.shape)
t1
t2=t1.reshape(-1)
# print(t2.shape)
t2


(2, 1, 1)


array([0, 1])

In [174]:
(20,10)+(1,)

(20, 10, 1)

In [34]:
xx=np.arange(2*10*1).reshape(2,10,1)
print(xx.shape)
xx

(2, 10, 1)


array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19]]])

In [ ]:
ss=np.max(xx,axis=1,keepdims=1)
print(ss.shape)
ss

In [38]:
ss=np.max(xx,axis=1,keepdims=1)
print(ss.shape)
ss

(2, 1, 1)


array([[[ 9]],

       [[19]]])

In [40]:
yy=xx-ss
print(yy.shape)
yy

(2, 10, 1)


array([[[-9],
        [-8],
        [-7],
        [-6],
        [-5],
        [-4],
        [-3],
        [-2],
        [-1],
        [ 0]],

       [[-9],
        [-8],
        [-7],
        [-6],
        [-5],
        [-4],
        [-3],
        [-2],
        [-1],
        [ 0]]])

In [45]:
zz=np.sum(yy,axis=1,keepdims=1)
print(zz.shape)
zz
# zz.squeeze
# zz

(2, 1, 1)


array([[[-45]],

       [[-45]]])

In [52]:
ll=yy/zz
print(ll.shape)
ll
mm=ll.reshape((1,)+ll.shape)
print(ll.shape)

(2, 10, 1)
(2, 10, 1)


In [256]:
np.trunc(d)

array([[[0.],
        [0.],
        [1.]],

       [[0.],
        [0.],
        [1.]],

       [[0.],
        [0.],
        [1.]]])

In [167]:
# xx=(1,1,1)
# xx = (:,1,1)
# a1[1,1,1]dd

array([[[[ 0,  1,  2],
         [12, 13, 14]]]])