In [5]:
import numpy as np
a=np.arange(9).reshape(1,9)+1
print(a)
b=np.ones((1,9))*2
print(b)
print(b/a)

[[1 2 3 4 5 6 7 8 9]]
[[2. 2. 2. 2. 2. 2. 2. 2. 2.]]
[[2.         1.         0.66666667 0.5        0.4        0.33333333
  0.28571429 0.25       0.22222222]]


In [6]:
np.log(1e-23)

-52.95945713886305

In [35]:
# a1=np.arange(10).reshape(1,-1)
a1=np.arange(10)
print(a1.shape)
# a1.argmax()
print(a1)


(10,)
[0 1 2 3 4 5 6 7 8 9]


In [38]:
b1=np.diag(a1)
print(b1.shape)
print(b1)

(10, 10)
[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 9]]
