In [1]:
import numpy as np
import mnist

In [21]:
# aa=np.arange(5).reshape(5,1)
aa=np.arange(5).reshape(-1,1)
# aa=np.arange(5)
# assert(aa.shape==(-1,1))
assert(aa.shape==(5,1))
aa.shape
aa@aa.T
# type(aa)

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])

In [26]:
def relu(x,k=0): return nmax(k,x)

relu(-12,0.2)

0.2

In [58]:
import numpy as np 
class ann:
#    def bp(self,x,params):
#     def relu(x,k=0):   k=max(0,min(1,k)); return max(k*x,x)
#     def relu(x,k=0):k=(k if k>0 and k<1 else 0) ; return np.max(k*x,x)
#     def relu(x):  return  max(0,x)
#     def relu(x):  return  max(np.zeros(np.array(x).shape),x)
    def relu(x,k=0): return np.maximum(k,x)
    
x=np.arange(3)
y=0
np.array(y).shape
ann.relu(x)
# relu(22)

array([0, 1, 2])

In [3]:
def d_relu(x): return (1 if x>0 else 0)
d_relu(22)


1

In [7]:
# coding:utf-8
# python3.10

student = {"NAME":{"label":"名称","fieldName":"NAME"},"ADDRESS":{"label":"地址","fieldName":"ADDRESS"},"LON":{"label":"经度","fieldName":"LON"},"LAT":{"label":"纬度","fieldName":"LAT"},"SOURCE":{"label":"数据来源","fieldName":"SOURCE"},"CITYCODE":{"label":"城市代码","fieldName":"CITYCODE"},"PRODATE":{"label":"处理日期","fieldName":"PRODATE"}}


student['NAME']['label']

'名称'

In [23]:
import numpy as np 
x=[-2,2]

def relu(x): return np.maximum(0,x)
relu(x)
y=(np.sign(x)+1)/2
y


array([0., 1.])

In [26]:
y=np.eye(3)[2].reshape(-1,1)
y2=np.maximum(1e-6,y)
y2

array([[1.e-06],
       [1.e-06],
       [1.e+00]])

In [53]:
tt={}
tt['aa']=[11,22,33]
tt['bb']=[44,55,66]
tt['cc']=np.arange(3*3).reshape(3,3)

tt

{'aa': [11, 22, 33],
 'bb': [44, 55, 66],
 'cc': array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])}

In [64]:
for (k,v) in tt.items():
    print(k)
    print(v)
    for i in range(len(v)):
        v[i]+=2
tt

aa
[12, 23, 34]
bb
[45, 56, 67]
cc
[[1 2 3]
 [4 5 6]
 [7 8 9]]


{'aa': [14, 25, 36],
 'bb': [47, 58, 69],
 'cc': array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])}

In [47]:
for k,v in tt.items():
    print(k)
    print(v)
    for i in v :
        print(i)
        i+=2 
    
#     v=v+2
tt


aa
[11, 22, 33]
11
22
33
bb
[44, 55, 66]
44
55
66


{'aa': [11, 22, 33], 'bb': [44, 55, 66]}

In [37]:
for v in tt['aa']:
    tt['aa'](v)+=2
tt




SyntaxError: 'function call' is an illegal expression for augmented assignment (1508829061.py, line 2)

In [36]:
for i in range(len(tt['aa'])):
    tt['aa'][i]+=2
tt

{'aa': [13, 24, 35], 'bb': 22}

In [52]:
aa=np.arange(3*3).reshape(3,3)
# aa
for i in range(len(aa)):
    print(aa[i]+1)

[1 2 3]
[4 5 6]
[7 8 9]
