In [12]:
import numpy as np

a1=np.arange(2*2).reshape(2,2)
A1=np.array([a1*3,a1])
b1=np.eye(2)
b2=np.eye(2)*2
B1=np.array([b1,b2])
Y1=A1@B1
print(A1)
print(B1)
print(Y1)

[[[0 3]
  [6 9]]

 [[0 1]
  [2 3]]]
[[[1. 0.]
  [0. 1.]]

 [[2. 0.]
  [0. 2.]]]
[[[0. 3.]
  [6. 9.]]

 [[0. 2.]
  [4. 6.]]]


In [85]:
import numpy as np

a1=np.arange(2*3).reshape(2,3)
print(a1.shape)
print(a1)

(2, 3)
[[0 1 2]
 [3 4 5]]


In [86]:
# b1=np.ones((1,1)+(a1.shape))
b1=np.ones((3))
b2=np.array([b1,b1*2]).T
print(b2.shape)
print(b2)

(3, 2)
[[1. 2.]
 [1. 2.]
 [1. 2.]]


In [90]:
# d1=np.einsum('ijk,lmn->ijklmn',a1,b2)
d1=np.einsum('ij,jl->ijl',a1,b2)
print(d1.shape)
print(d1)

(2, 3, 2)
[[[ 0.  0.]
  [ 1.  2.]
  [ 2.  4.]]

 [[ 3.  6.]
  [ 4.  8.]
  [ 5. 10.]]]


In [93]:
np.exp(d1)

array([[[1.00000000e+00, 1.00000000e+00],
        [2.71828183e+00, 7.38905610e+00],
        [7.38905610e+00, 5.45981500e+01]],

       [[2.00855369e+01, 4.03428793e+02],
        [5.45981500e+01, 2.98095799e+03],
        [1.48413159e+02, 2.20264658e+04]]])

In [30]:
d1=np.einsum('ijk,mln->ijkmln',a1,b2)
print(d1.shape)
print(d1)

(2, 3, 4, 2, 4, 2)
[[[[[[ 0.  0.]
     [ 0.  0.]
     [ 0.  0.]
     [ 0.  0.]]

    [[ 0.  0.]
     [ 0.  0.]
     [ 0.  0.]
     [ 0.  0.]]]


   [[[ 1.  1.]
     [ 1.  1.]
     [ 1.  1.]
     [ 1.  1.]]

    [[ 2.  2.]
     [ 2.  2.]
     [ 2.  2.]
     [ 2.  2.]]]


   [[[ 2.  2.]
     [ 2.  2.]
     [ 2.  2.]
     [ 2.  2.]]

    [[ 4.  4.]
     [ 4.  4.]
     [ 4.  4.]
     [ 4.  4.]]]


   [[[ 3.  3.]
     [ 3.  3.]
     [ 3.  3.]
     [ 3.  3.]]

    [[ 6.  6.]
     [ 6.  6.]
     [ 6.  6.]
     [ 6.  6.]]]]



  [[[[ 4.  4.]
     [ 4.  4.]
     [ 4.  4.]
     [ 4.  4.]]

    [[ 8.  8.]
     [ 8.  8.]
     [ 8.  8.]
     [ 8.  8.]]]


   [[[ 5.  5.]
     [ 5.  5.]
     [ 5.  5.]
     [ 5.  5.]]

    [[10. 10.]
     [10. 10.]
     [10. 10.]
     [10. 10.]]]


   [[[ 6.  6.]
     [ 6.  6.]
     [ 6.  6.]
     [ 6.  6.]]

    [[12. 12.]
     [12. 12.]
     [12. 12.]
     [12. 12.]]]


   [[[ 7.  7.]
     [ 7.  7.]
     [ 7.  7.]
     [ 7.  7.]]

    [[14. 14.]
     [14. 14.]
     

In [29]:
c1=np.einsum('ijk,mli->ijkml',a1,b2)
print(c1.shape)
print(c1)

(2, 3, 4, 2, 4)
[[[[[ 0.  0.  0.  0.]
    [ 0.  0.  0.  0.]]

   [[ 1.  1.  1.  1.]
    [ 2.  2.  2.  2.]]

   [[ 2.  2.  2.  2.]
    [ 4.  4.  4.  4.]]

   [[ 3.  3.  3.  3.]
    [ 6.  6.  6.  6.]]]


  [[[ 4.  4.  4.  4.]
    [ 8.  8.  8.  8.]]

   [[ 5.  5.  5.  5.]
    [10. 10. 10. 10.]]

   [[ 6.  6.  6.  6.]
    [12. 12. 12. 12.]]

   [[ 7.  7.  7.  7.]
    [14. 14. 14. 14.]]]


  [[[ 8.  8.  8.  8.]
    [16. 16. 16. 16.]]

   [[ 9.  9.  9.  9.]
    [18. 18. 18. 18.]]

   [[10. 10. 10. 10.]
    [20. 20. 20. 20.]]

   [[11. 11. 11. 11.]
    [22. 22. 22. 22.]]]]



 [[[[12. 12. 12. 12.]
    [24. 24. 24. 24.]]

   [[13. 13. 13. 13.]
    [26. 26. 26. 26.]]

   [[14. 14. 14. 14.]
    [28. 28. 28. 28.]]

   [[15. 15. 15. 15.]
    [30. 30. 30. 30.]]]


  [[[16. 16. 16. 16.]
    [32. 32. 32. 32.]]

   [[17. 17. 17. 17.]
    [34. 34. 34. 34.]]

   [[18. 18. 18. 18.]
    [36. 36. 36. 36.]]

   [[19. 19. 19. 19.]
    [38. 38. 38. 38.]]]


  [[[20. 20. 20. 20.]
    [40. 40. 40. 40.]]

   [[2