In [108]:
import cnn
import numpy as np
import imp
imp.reload(cnn)
# (params,params_init,g,g_d)=cnn.init_params(lays=2)
# params=cnn.hyperparams_test(params,params_init,g,g_d,nloop=4,lr0=2e-3,klr=0.9995,batch=64,isupdate=1,isl2grad=1)
# cnn.show(params,g)

params: ch= [1, 2, 3, 4, 10]
params: lays= 4
params: k0.shape= (2, 1, 3, 3)
params: gama0.shape= (2, 1, 1)
params: beta0.shape= (2, 1, 1)
params: k1.shape= (3, 2, 3, 3)
params: gama1.shape= (3, 1, 1)
params: beta1.shape= (3, 1, 1)
params: k2.shape= (4, 3, 3, 3)
params: gama2.shape= (4, 1, 1)
params: beta2.shape= (4, 1, 1)
params: w3.shape= (10, 4, 5, 6)
x.shape= (2, 1, 5, 6)
bp: gama2.shape= (4, 1, 1)
bp: d_Y2.shape= (2, 4, 5, 6)
bp: d_X2.shape= (2, 4, 5, 6)
bp: k2.shape= (4, 3, 3, 3)
bp: k2_fl.shape= (4, 3, 3, 3)
bp: gama1.shape= (3, 1, 1)
bp: d_Y1.shape= (2, 3, 5, 6)
bp: d_X1.shape= (2, 3, 5, 6)
bp: k1.shape= (3, 2, 3, 3)
bp: k1_fl.shape= (3, 2, 3, 3)
bp: gama0.shape= (2, 1, 1)
bp: d_Y0.shape= (2, 2, 5, 6)
bp: d_X0.shape= (2, 2, 5, 6)
bp: k0.shape= (2, 1, 3, 3)
bp: k0_fl.shape= (2, 1, 3, 3)
slope: running k0.shape= (2, 1, 3, 3)
slope: k0[1/18] slope = 1.900668357457391
slope: k0[2/18] slope = -1.081241118949805
slope: k0[3/18] slope = 1.8463836932269826
slope: k0[4/18] slope = 2.2991

<module 'cnn' from '/home/qc/proj_py/cnn.py'>

In [109]:
0.84523397*2

1.69046794

In [ ]:
grad[d_k2]=
 [[[[-0.0733586  -0.23462498 -0.56445454]
   [ 0.58235965 -0.05411912 -0.34167744]
   [ 0.52121295 -0.07754757 -0.29606999]]

  [[ 0.18012191 -0.6908719  -0.22410318]
   [ 0.63605583 -0.79904314  0.36796845]
   [-0.23434101 -0.07363184 -0.78729009]]

  [[-0.01626022 -0.44843178  0.27737338]
   [ 0.70212899 -0.10441041  0.76325581]
   [-0.17916734 -0.03472223  0.12165029]]]