In [140]:
import numpy as np
from timeit import timeit 
# (ba,h,w)=(2,4,5)
(ba,h,w)=(16,28,28)
a1=np.arange(ba*h*w).reshape(ba,h,w)
a2=np.arange(ba*h*w).reshape(ba,-1,1)
a3=np.einsum('mij,mkl->mijkl',a1,a1)
print('time @:')
%timeit -n10 a2@a2.transpose(0,2,1)
print('time einsum 1:')
%timeit -n10  np.einsum('mij,mkl->mijkl',a1,a1)
print('time einsum 2:')
%timeit -n10  np.einsum('mij,mkj->mik',a2,a2)
print('time einsum 3:')
%timeit -n10  np.einsum('mijij->mij',a3)[:]=h*w
# %timeit np.argmax(a3,1)
# %timeit np.argmin(a3,1)
# %timeit np.sum(a3,1)/a3.shape[1]
# %timeit np.sum(a3,1)/10


time @:
50.2 ms ± 726 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
time einsum 1:
67.3 ms ± 1.63 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
time einsum 2:
67.3 ms ± 1.84 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
time einsum 3:
70.4 µs ± 23.9 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [131]:
import numpy as np
t1=np.mean(a3,(1,2))
t2=np.mean(a3,0)
nn=np.arange(1,a3.ndim-1)
# t3=np.sum(a3,nn)
# t3=np.mean(a3,(0,2))
# t3=np.mean(a3,-2)
print('t1.shape=',t1.shape)
print('t2.shape=',t2.shape)
print('t3.shape=',t3.shape)
nn

t1.shape= (2,)
t2.shape= (4, 5)
t3.shape= (4,)


array([1])

In [17]:
import numpy as np
ba=3
# l1=np.zeros((ba,1),dtype=int)
# l1[:,0]=np.arange(ba)+2
# l1=l1.reshape(-1)
# l1=np.random.randint(10,size=(ba,1))
l1=np.random.randint(10,size=(ba))
print('l1.shape=',l1.shape)
print('l1=\n',l1)
lv1=np.zeros((ba,10,1))
print('lv1.shape=',lv1.shape)
nba=np.arange(ba)
print('nba.shape=',nba.shape)
print('nba=\n',nba)
# x2=lv1[np.arange(ba),l1,0]
# x2[:]=1
# lv1[np.arange(ba),l1,0][:]=1
# lv1[np.arange(ba),0,0][:]=1
# lv1[:,l1,0][:]=1
# lv1[np.arange(ba),l1,0]=1
lv1[np.arange(ba),l1,:]=1
# lv1[0,1,:][:]=1
# x2=lv1[np.arange(ba),l1,:]
print('np.arange(ba).shape=',np.arange(ba).shape)
# print('x2.shape=',x2.shape)
# print('x2=\n',x2)
print('lv1.shape=',lv1.shape)
# print('lv1=\n',lv1.T)
print('lv1=\n',lv1.transpose(0,2,1))

l1.shape= (3,)
l1=
 [8 0 5]
lv1.shape= (3, 10, 1)
nba.shape= (3,)
nba=
 [0 1 2]
np.arange(ba).shape= (3,)
lv1.shape= (3, 10, 1)
lv1=
 [[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]

 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]]


In [171]:
import numpy as np
a1=np.random.randint(10,size=(1,5))
b1=1.0
c1=np.array(0.0)
print('c1.shape=',c1.shape)
print('c1.dtype=',c1.dtype)
print('c1=\n',c1)

c1.shape= ()
c1.dtype= float64
c1=
 0.0
