In [12]:
import numpy as np

a1=np.arange(2*2).reshape(2,2)
A1=np.array([a1*3,a1])
b1=np.eye(2)
b2=np.eye(2)*2
B1=np.array([b1,b2])
Y1=A1@B1
print(A1)
print(B1)
print(Y1)

[[[0 3]
  [6 9]]

 [[0 1]
  [2 3]]]
[[[1. 0.]
  [0. 1.]]

 [[2. 0.]
  [0. 2.]]]
[[[0. 3.]
  [6. 9.]]

 [[0. 2.]
  [4. 6.]]]


In [30]:
import numpy as np

def softmax(x): 
    exp=np.exp(x-x.max())
    return exp/exp.sum()
def softmax_d(x): 
    print('softmax x shape:',x.shape)
    y=softmax(x)
    print('softmax y shape:',y.shape)
    return np.diag(y[:,0])-np.outer(y,y)


In [39]:
x=np.arange(2*3*1).reshape(2,3)
x.shape

(2, 3)

In [40]:
x[:,0,:]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [37]:
y=softmax(x)
y.shape
y

array([[[0.00426978],
        [0.01160646],
        [0.03154963]],

       [[0.08576079],
        [0.23312201],
        [0.63369132]]])

In [38]:
y[0]

array([[0.00426978],
       [0.01160646],
       [0.03154963]])