In [23]:
import numpy as np
def im2col(im,k=3,s=1,pad=1):
    if k==1: col=np.expand_dims(im,(-2,-1))
    else:
        p=int(k/2)
        (ba,c,h,w)=im.shape
        if pad==1: imp=np.pad(im,((0,0),(0,0),(p,p),(p,p)))
        else: imp=im
        (ba,c,hp,wp)=imp.shape
        strd=(c*hp*wp,hp*wp,wp*s,s,wp,1)
        strd=(i*imp.itemsize for i in strd)
        col=np.lib.stride_tricks.as_strided(imp,shape=(ba,c,int((hp-k)/s)+1,int((wp-k)/s)+1,k,k),strides=strd)
    return col

def conv(Ai_1,ki,d_Zi=None):
    Ci_1=im2col(Ai_1,ki.shape[-1])
    Zi=np.einsum('bchwij,mcij->bmchw',Ci_1,ki)
    if d_Zi is None: return Zi
    else:
        ki_fl=np.flip(ki,(-2,-1))
        d_Zi_2col=im2col(d_Zi,ki_fl.shape[-1])
        d_Ai_1=np.einsum('bmhwij,mcij->bchw',d_Zi_2col,ki_fl)
        return Zi,d_Ai_1
    
import numpy as np
A0=np.arange(2*2*4*4).reshape(2,2,4,4)+1
k1=np.arange(3*2*3*3).reshape(3,2,3,3)
d_Z1=np.arange(2*3*4*4).reshape(2,3,4,4)*0.1
# Z1,d_A0=conv(A0,k1,d_Zi=d_Z1)
Z1,d_A0=conv(A0,k1,d_Z1)

print('A0=\n',A0)
print('Z1=\n',Z1)
print('d_A0=\n',d_A0)
print('A0.shape=',A0.shape)
print('Z1.shape=',Z1.shape)
print('d_A0.shape=',d_A0.shape)


A0=
 [[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]
   [25 26 27 28]
   [29 30 31 32]]]


 [[[33 34 35 36]
   [37 38 39 40]
   [41 42 43 44]
   [45 46 47 48]]

  [[49 50 51 52]
   [53 54 55 56]
   [57 58 59 60]
   [61 62 63 64]]]]
Z1=
 [[[[[   97   154   187   123]
    [  198   294   330   207]
    [  306   438   474   291]
    [  151   202   217   121]]

   [[ 1183  1762  1849  1217]
    [ 1791  2652  2769  1812]
    [ 2115  3120  3237  2112]
    [ 1333  1954  2023  1311]]]


  [[[  349   586   727   519]
    [  792  1266  1464  1017]
    [ 1332  2058  2256  1533]
    [  979  1498  1621  1093]]

   [[ 2587  3922  4117  2765]
    [ 4113  6216  6495  4350]
    [ 4869  7332  7611  5082]
    [ 3313  4978  5155  3435]]]


  [[[  601  1018  1267   915]
    [ 1386  2238  2598  1827]
    [ 2358  3678  4038  2775]
    [ 1807  2794  3025  2065]]

   [[ 3991  6082  6385  4313]
    [ 6435  9780 10221  6888]
    [ 7623 11544 11985  8052]
   

In [32]:
import numpy as np
a1=np.arange(2*2*4*4).reshape(2,2,4,4)-22
b1=a1.copy()
b1[b1<0]=0
c1=b1.copy()
c1[c1>0]=1

print('a1=\n',a1)
print('c1=\n',c1)
print('b1=\n',b1)


a1=
 [[[[-22 -21 -20 -19]
   [-18 -17 -16 -15]
   [-14 -13 -12 -11]
   [-10  -9  -8  -7]]

  [[ -6  -5  -4  -3]
   [ -2  -1   0   1]
   [  2   3   4   5]
   [  6   7   8   9]]]


 [[[ 10  11  12  13]
   [ 14  15  16  17]
   [ 18  19  20  21]
   [ 22  23  24  25]]

  [[ 26  27  28  29]
   [ 30  31  32  33]
   [ 34  35  36  37]
   [ 38  39  40  41]]]]
c1=
 [[[[0 0 0 0]
   [0 0 0 0]
   [0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 1]
   [1 1 1 1]
   [1 1 1 1]]]


 [[[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]]]
b1=
 [[[[ 0  0  0  0]
   [ 0  0  0  0]
   [ 0  0  0  0]
   [ 0  0  0  0]]

  [[ 0  0  0  0]
   [ 0  0  0  1]
   [ 2  3  4  5]
   [ 6  7  8  9]]]


 [[[10 11 12 13]
   [14 15 16 17]
   [18 19 20 21]
   [22 23 24 25]]

  [[26 27 28 29]
   [30 31 32 33]
   [34 35 36 37]
   [38 39 40 41]]]]


In [14]:
import numpy as np
# def im2col(im,k=3,s=1,pad=1):
#     p=int(k/2)
#     (ba,c,h,w)=im.shape
#     if pad==1: imp=np.pad(im,((0,0),(0,0),(p,p),(p,p)))
#     else: imp=im
#     (ba,c,hp,wp)=imp.shape
#     strd=(c*hp*wp,hp*wp,wp*s,s,wp,1)
#     strd=(i*imp.itemsize for i in strd)
#     col=np.lib.stride_tricks.as_strided(imp,shape=(ba,c,int((hp-k)/s)+1,int((wp-k)/s)+1,k,k),strides=strd)
#     return col

def im2col(im,k=3,s=1,pad=1):
    if k==1: col=np.expand_dims(im,(-2,-1))
    else:
        p=int(k/2)
        (ba,c,h,w)=im.shape
        if pad==1: imp=np.pad(im,((0,0),(0,0),(p,p),(p,p)))
        else: imp=im
        (ba,c,hp,wp)=imp.shape
        strd=(c*hp*wp,hp*wp,wp*s,s,wp,1)
        strd=(i*imp.itemsize for i in strd)
        col=np.lib.stride_tricks.as_strided(imp,shape=(ba,c,int((hp-k)/s)+1,int((wp-k)/s)+1,k,k),strides=strd)
    return col


a1=np.arange(1*2*4*4).reshape(1,2,4,4)+1
# b1=im2col(a1,k=1)
b1=im2col(a1,1)

print('a1=\n',a1)
print('b1=\n',b1.squeeze())
print('a1.shape=',a1.shape)
print('b1.shape=',b1.shape)



a1=
 [[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]
   [25 26 27 28]
   [29 30 31 32]]]]
b1=
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]]
a1.shape= (1, 2, 4, 4)
b1.shape= (1, 2, 4, 4, 1, 1)


In [43]:
import numpy as np
np.log2(7)



2.807354922057604

In [ ]:
a2=
 [[[[ 0  0  0  0  0  0]
   [ 0  1  2  3  4  0]
   [ 0  5  6  7  8  0]
   [ 0  9 10 11 12  0]
   [ 0 13 14 15 16  0]
   [ 0  0  0  0  0  0]]

  [[ 0  0  0  0  0  0]
   [ 0 17 18 19 20  0]
   [ 0 21 22 23 24  0]
   [ 0 25 26 27 28  0]
   [ 0 29 30 31 32  0]
   [ 0  0  0  0  0  0]]]]