In [4]:
import numpy as np
a=np.ones((5,3))
print('a.shape=',a.shape)
# print('a=\n',a)
b=np.arange(2*3*4*1).reshape(2,3,4,1)
print('b.shape=',b.shape)
print('b=\n',b)
c=np.einsum('ij,mjkn->mikn',a,b)
print('c.shape=',c.shape)
print('c=\n',c)


a.shape= (5, 3)
b.shape= (2, 3, 4, 1)
b=
 [[[[ 0]
   [ 1]
   [ 2]
   [ 3]]

  [[ 4]
   [ 5]
   [ 6]
   [ 7]]

  [[ 8]
   [ 9]
   [10]
   [11]]]


 [[[12]
   [13]
   [14]
   [15]]

  [[16]
   [17]
   [18]
   [19]]

  [[20]
   [21]
   [22]
   [23]]]]
c.shape= (2, 5, 4, 1)
c=
 [[[[12.]
   [15.]
   [18.]
   [21.]]

  [[12.]
   [15.]
   [18.]
   [21.]]

  [[12.]
   [15.]
   [18.]
   [21.]]

  [[12.]
   [15.]
   [18.]
   [21.]]

  [[12.]
   [15.]
   [18.]
   [21.]]]


 [[[48.]
   [51.]
   [54.]
   [57.]]

  [[48.]
   [51.]
   [54.]
   [57.]]

  [[48.]
   [51.]
   [54.]
   [57.]]

  [[48.]
   [51.]
   [54.]
   [57.]]

  [[48.]
   [51.]
   [54.]
   [57.]]]]


In [12]:
import numpy as np
# a=np.arange(2*3).reshape(2,3)+1
a=np.ones((2,3))
c=np.arange(2*2*2*3).reshape(2,2,2,3)+1
print('a.shape=',a.shape)
print('a=\n',a)
print('c.shape=',c.shape)
print('c=\n',c)
b=np.einsum('mnij,ij->mn',c,a)
print('b.shape=',b.shape)
print('b=\n',b)


a.shape= (2, 3)
a=
 [[1. 1. 1.]
 [1. 1. 1.]]
c.shape= (2, 2, 2, 3)
c=
 [[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]]]]
b.shape= (2, 2)
b=
 [[ 21.  57.]
 [ 93. 129.]]
