In [9]:
import numpy as np

aa=np.arange(3)
print('aa')
print(aa)
print(aa.shape)

bb=np.arange(3).reshape(-1,1)
print('bb')
print(bb)
print(bb.shape)

cc=np.outer(aa,aa)
print('cc')
print(cc.shape)
print(cc)

dd=np.outer(bb,bb)
print('dd')
print(dd.shape)
print(dd)




aa
[0 1 2]
(3,)
bb
[[0]
 [1]
 [2]]
(3, 1)
cc
(3, 3)
[[0 0 0]
 [0 1 2]
 [0 2 4]]
dd
(3, 3)
[[0 0 0]
 [0 1 2]
 [0 2 4]]
