In [58]:
a1=100
99%10

9

In [51]:
import numpy as np
a1=np.arange(2*2*4*5).reshape(1,1,2,2,4,5,1,1)+1
b1=a1.squeeze()
# b1=a1.squeeze()
# b1=np.squeeze(a1)
print('a1.shape=',a1.shape)
print('b1.shape=',b1.shape)

a1.shape= (1, 1, 2, 2, 4, 5, 1, 1)
b1.shape= (2, 2, 4, 5)


In [61]:
import numpy as np
a1=np.arange(3*3).reshape(3,3)+1
print('a1=\n',a1)
b1=np.flip(a1)
# b1=a1.squeeze()
# b1=np.squeeze(a1)
print('a1=\n',a1)
print('b1=\n',b1)
print('a1.shape=',a1.shape)
print('b1.shape=',b1.shape)

a1=
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
a1=
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
b1=
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
a1.shape= (3, 3)
b1.shape= (3, 3)


In [14]:
a1=
 [[[[ 1  2  3  4  5]
   [ 6  7  8  9 10]
   [11 12 13 14 15]
   [16 17 18 19 20]]

  [[21 22 23 24 25]
   [26 27 28 29 30]
   [31 32 33 34 35]
   [36 37 38 39 40]]]


 [[[41 42 43 44 45]
   [46 47 48 49 50]
   [51 52 53 54 55]
   [56 57 58 59 60]]

  [[61 62 63 64 65]
   [66 67 68 69 70]
   [71 72 73 74 75]
   [76 77 78 79 80]]]]

a1=
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
b1=
 [[[17 16]
  [15 14]
  [13 12]]

 [[11 10]
  [ 9  8]
  [ 7  6]]

 [[ 5  4]
  [ 3  2]
  [ 1  0]]]
a1.shape= (3, 3, 2)
b1.shape= (3, 3, 2)
