In [58]:
a1=100
99%10

9

In [51]:
import numpy as np
a1=np.arange(2*2*4*5).reshape(1,1,2,2,4,5,1,1)+1
b1=a1.squeeze()
# b1=a1.squeeze()
# b1=np.squeeze(a1)
print('a1.shape=',a1.shape)
print('b1.shape=',b1.shape)

a1.shape= (1, 1, 2, 2, 4, 5, 1, 1)
b1.shape= (2, 2, 4, 5)


In [26]:
import numpy as np
a1=np.arange(2*2*4*5).reshape(2,2,4,5)+1
(ba,c,h,w)=a1.shape
(ba,cp,hp,wp)=(ba,c,h-2,w-2)
# strd=(cp*hp*wp,hp*wp,wp,1,wp,1)
strd=(c*h*w,h*w,w,1,w,1)
strd=(i*a1.itemsize for i in strd)
col=np.lib.stride_tricks.as_strided(a1,shape=(ba,cp,hp,wp,3,3),strides=strd)
print('a1=\n',a1)
print('col=\n',col)
print('col[1]=\n',col[1])
print('col[1,1]=\n',col[1,1])
print('a1.shape=',a1.shape)
print('col.shape=',col.shape)

a1=
 [[[[ 1  2  3  4  5]
   [ 6  7  8  9 10]
   [11 12 13 14 15]
   [16 17 18 19 20]]

  [[21 22 23 24 25]
   [26 27 28 29 30]
   [31 32 33 34 35]
   [36 37 38 39 40]]]


 [[[41 42 43 44 45]
   [46 47 48 49 50]
   [51 52 53 54 55]
   [56 57 58 59 60]]

  [[61 62 63 64 65]
   [66 67 68 69 70]
   [71 72 73 74 75]
   [76 77 78 79 80]]]]
col=
 [[[[[[ 1  2  3]
     [ 6  7  8]
     [11 12 13]]

    [[ 2  3  4]
     [ 7  8  9]
     [12 13 14]]

    [[ 3  4  5]
     [ 8  9 10]
     [13 14 15]]]


   [[[ 6  7  8]
     [11 12 13]
     [16 17 18]]

    [[ 7  8  9]
     [12 13 14]
     [17 18 19]]

    [[ 8  9 10]
     [13 14 15]
     [18 19 20]]]]



  [[[[21 22 23]
     [26 27 28]
     [31 32 33]]

    [[22 23 24]
     [27 28 29]
     [32 33 34]]

    [[23 24 25]
     [28 29 30]
     [33 34 35]]]


   [[[26 27 28]
     [31 32 33]
     [36 37 38]]

    [[27 28 29]
     [32 33 34]
     [37 38 39]]

    [[28 29 30]
     [33 34 35]
     [38 39 40]]]]]




 [[[[[41 42 43]
     [46 47 48]
     [51 52 

In [14]:
a1=
 [[[[ 1  2  3  4  5]
   [ 6  7  8  9 10]
   [11 12 13 14 15]
   [16 17 18 19 20]]

  [[21 22 23 24 25]
   [26 27 28 29 30]
   [31 32 33 34 35]
   [36 37 38 39 40]]]


 [[[41 42 43 44 45]
   [46 47 48 49 50]
   [51 52 53 54 55]
   [56 57 58 59 60]]

  [[61 62 63 64 65]
   [66 67 68 69 70]
   [71 72 73 74 75]
   [76 77 78 79 80]]]]

a1=
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
b1=
 [[[17 16]
  [15 14]
  [13 12]]

 [[11 10]
  [ 9  8]
  [ 7  6]]

 [[ 5  4]
  [ 3  2]
  [ 1  0]]]
a1.shape= (3, 3, 2)
b1.shape= (3, 3, 2)
