In [30]:
import numpy as np
import copy
def relu(x,kn=1e-3):
    y=copy.deepcopy(x) .reshape(-1)
    yt=x.reshape(-1)
    y[yt<0]=y[yt<0]*kn
    y[yt>=0]=y[yt>=0]
    y=y.reshape(x.shape)
    return y
def relu_d(x,kn=1e-3):
    y=copy.deepcopy(x) .reshape(-1)
#     y=y.reshape(-1)
    yt=x.reshape(-1)
#     print('yt=',yt)
#     print('y=',y)
    y[yt<0]=kn
    y[yt>=0]=1
    print('yt=',yt)
    print('y=',y)
    print('x=',x)
    y=y.reshape(x.shape)
    return y

In [32]:
print(relu)
print(dir(relu))

<function relu at 0x7f14a45b6830>
['__annotations__', '__builtins__', '__call__', '__class__', '__closure__', '__code__', '__defaults__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__get__', '__getattribute__', '__globals__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__kwdefaults__', '__le__', '__lt__', '__module__', '__name__', '__ne__', '__new__', '__qualname__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']


In [16]:
a1=np.arange(3*2*2,dtype=np.float32).reshape(3,2,2)
# a1=np.arange(3*2*2).reshape(3,2,2)
a1=a1-6
print(a1.shape)
print(a1)

(3, 2, 2)
[[[-6. -5.]
  [-4. -3.]]

 [[-2. -1.]
  [ 0.  1.]]

 [[ 2.  3.]
  [ 4.  5.]]]


In [28]:
relu(a1)

array([[[-6.0000001e-03, -5.0000004e-03],
        [-4.0000002e-03, -3.0000000e-03]],

       [[-2.0000001e-03, -1.0000000e-03],
        [ 0.0000000e+00,  1.0000000e+00]],

       [[ 2.0000000e+00,  3.0000000e+00],
        [ 4.0000000e+00,  5.0000000e+00]]], dtype=float32)

In [29]:
relu_d(a1)

yt= [-6. -5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
y= [0.001 0.001 0.001 0.001 0.001 0.001 1.    1.    1.    1.    1.    1.   ]
x= [[[-6. -5.]
  [-4. -3.]]

 [[-2. -1.]
  [ 0.  1.]]

 [[ 2.  3.]
  [ 4.  5.]]]


array([[[0.001, 0.001],
        [0.001, 0.001]],

       [[0.001, 0.001],
        [1.   , 1.   ]],

       [[1.   , 1.   ],
        [1.   , 1.   ]]], dtype=float32)